from __future__ import annotations

import argparse
import csv
import html
import json
import math
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt  # type: ignore
except Exception:  # pragma: no cover - optional dependency
    plt = None


ANALYSIS_SCHEMA_VERSION = "1.0.0"
ANALYSIS_DIR_NAME = "analysis"

OUTPUT_JSON = "analysis_report.json"
OUTPUT_SUMMARY_CSV = "analysis_summary.csv"
OUTPUT_METRICS_CSV = "analysis_metrics_long.csv"
OUTPUT_TRAINING_CSV = "analysis_training_long.csv"
OUTPUT_TOOLTIPS_CSV = "analysis_tooltips.csv"
OUTPUT_HTML = "analysis_report.html"
OUTPUT_FIG_DIR = "figs"
OUTPUT_FIG_COMPARISON = "comparison_metrics.png"
OUTPUT_FIG_LEAKAGE = "comparison_leakage.png"
OUTPUT_FIG_TRAINING = "training_curves.png"


STRUCTURE_METRICS = [
    ("od_jsd", "od", "OD JSD", True, "Distribution mismatch between OD marginals."),
    ("od_chi2", "od", "OD Chi²", True, "OD chi-square divergence for synthetic vs real."),
    ("od_coverage_real", "od", "OD coverage (real)", False, "Real OD support coverage (higher is better)."),
    ("od_coverage_synth", "od", "OD coverage (synth)", False, "Synthetic OD support coverage (higher is better)."),
    (
        "od_unique_real",
        "od",
        "OD unique modes (real)",
        False,
        "Unique OD modes observed in the real distribution.",
    ),
    (
        "od_unique_synth",
        "od",
        "OD unique modes (synth)",
        False,
        "Unique OD modes generated by synthetic samples.",
    ),
    ("joint_jsd", "joint", "Joint JSD", True, "Joint OD+time distribution mismatch."),
    ("joint_chi2", "joint", "Joint Chi²", True, "Joint OD+time chi-square divergence."),
    (
        "joint_coverage_real",
        "joint",
        "Joint coverage (real)",
        False,
        "Real joint support coverage (higher is better).",
    ),
    (
        "joint_coverage_synth",
        "joint",
        "Joint coverage (synth)",
        False,
        "Synthetic joint support coverage (higher is better).",
    ),
    (
        "joint_unique_real",
        "joint",
        "Joint unique modes (real)",
        False,
        "Unique OD+time mode count for real data.",
    ),
    (
        "joint_unique_synth",
        "joint",
        "Joint unique modes (synth)",
        False,
        "Unique OD+time mode count for synthetic data.",
    ),
    (
        "joint_mode_dropping_ratio",
        "joint",
        "Joint mode dropping ratio",
        True,
        "Portion of real joint modes that disappear in synthetic.",
    ),
    (
        "joint_invalid_ratio",
        "joint",
        "Joint invalid ratio",
        True,
        "Portion of invalid OD pairs in synthetic samples.",
    ),
]


KEY_ALIASES = {
    "od_coverage_real": (
        "od_coverage_real",
        "od_cov_real",
        "cov_real",
        "coverage_real",
    ),
    "od_coverage_synth": (
        "od_coverage_synth",
        "od_cov_syn",
        "cov_synth",
        "coverage_synth",
    ),
    "joint_coverage_real": (
        "joint_coverage_real",
        "joint_cov_real",
        "joint_coverage",
    ),
    "joint_coverage_synth": (
        "joint_coverage_synth",
        "joint_cov_synth",
        "joint_coverage_synth_real",
    ),
    "od_unique_real": ("od_unique_real", "od_unique"),
    "od_unique_synth": ("od_unique_synth",),
    "joint_unique_real": ("joint_unique_real",),
    "joint_unique_synth": ("joint_unique_synth",),
    "joint_invalid_ratio": ("joint_invalid_ratio",),
}


COMPARE_DIRECTIONS = [
    ("synth->val", "strategy_val"),
    ("synth->hold", "strategy_hold"),
    ("hold->val", "strategy_hold_vs_val_real"),
]


TRAINING_RECORDS = ("loss", "scalars", "log")


def _safe_float(value: Any) -> float | None:
    if value is None:
        return None
    if isinstance(value, bool):
        return float(value)
    if isinstance(value, (int, float)):
        return float(value)
    try:
        parsed = float(str(value).strip())
    except (TypeError, ValueError):
        return None
    if math.isfinite(parsed):
        return parsed
    return None


def _read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as fh:
        payload = json.load(fh)
    if isinstance(payload, Mapping):
        return dict(payload)
    raise TypeError(f"invalid JSON payload in {path}: expected object")


def _to_csv_value(value: Any) -> str | int | float | bool:
    if value is None:
        return ""
    if isinstance(value, bool):
        return value
    if isinstance(value, float):
        return value if not math.isnan(value) else ""
    if isinstance(value, (int, str)):
        return value
    return str(value)


def _metric_aliases(key: str) -> tuple[str, ...]:
    return KEY_ALIASES.get(key, (key,))


def _metric_from_section(section: Mapping[str, Any], metric_key: str) -> float | None:
    metrics = section.get("metrics", {})
    if not isinstance(metrics, Mapping):
        return None
    for candidate in _metric_aliases(metric_key):
        value = _safe_float(metrics.get(candidate))
        if value is not None:
            return value
    return None


def _flatten_sections(bundle: Mapping[str, Any]) -> Mapping[str, Mapping[str, Any]]:
    sections = bundle.get("sections")
    if isinstance(sections, Mapping):
        return {str(k): dict(v) for k, v in sections.items() if isinstance(v, Mapping)}
    return {}


def _collect_metric_comparison_rows(
    metrics_sections: Mapping[str, Mapping[str, Any]],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    metric_rows: list[dict[str, Any]] = []
    summary_rows: list[dict[str, Any]] = []

    for metric_key, family, metric_label, lower_is_better, description in STRUCTURE_METRICS:
        direction_values: dict[str, float | None] = {}
        for direction, section_name in COMPARE_DIRECTIONS:
            section = metrics_sections.get(section_name, {})
            status = section.get("status", "missing")
            source_file = section.get("source_file")
            value = _metric_from_section(section, metric_key)
            direction_values[direction] = value
            metric_rows.append(
                {
                    "record_type": "metric_point",
                    "metric_family": family,
                    "metric_key": metric_key,
                    "metric_label": metric_label,
                    "direction": direction,
                    "run_section": section_name,
                    "value": value,
                    "value_type": type(value).__name__ if value is not None else "missing",
                    "lower_is_better": lower_is_better,
                    "status": status,
                    "source_file": source_file if source_file is not None else "",
                    "tooltip_id": metric_key,
                    "description": description,
                }
            )

        synth_to_val = direction_values.get("synth->val")
        synth_to_hold = direction_values.get("synth->hold")
        hold_to_val = direction_values.get("hold->val")

        # Derived indicators:
        # 1) How much additional variation appears in synth->val relative to natural hold->val variation.
        # 2) Whether the synthetic distribution drift from hold to val is larger than synthetic->hold.
        derived_abs_gap = None
        relative_gap = None
        synthetic_generalization = None
        risk_level = "unknown"
        if (
            synth_to_val is not None
            and hold_to_val is not None
        ):
            derived_abs_gap = abs(synth_to_val - hold_to_val)
            if hold_to_val != 0:
                relative_gap = derived_abs_gap / abs(hold_to_val)
            if lower_is_better:
                if relative_gap is None:
                    risk_level = "unknown"
                elif relative_gap <= 0.10:
                    risk_level = "low"
                elif relative_gap <= 0.25:
                    risk_level = "medium"
                else:
                    risk_level = "high"
            else:
                if relative_gap is None:
                    risk_level = "unknown"
                elif relative_gap <= 0.10:
                    risk_level = "low"
                elif relative_gap <= 0.25:
                    risk_level = "medium"
                else:
                    risk_level = "high"

        if (
            synth_to_val is not None
            and synth_to_hold is not None
            and hold_to_val is not None
        ):
            synthetic_generalization = (synth_to_val - hold_to_val) - (synth_to_hold - hold_to_val)

        summary_rows.append(
            {
                "record_type": "comparison_summary",
                "metric_family": family,
                "metric_key": metric_key,
                "metric_label": metric_label,
                "lower_is_better": lower_is_better,
                "tooltip_id": metric_key,
                "synth_to_val": synth_to_val,
                "synth_to_hold": synth_to_hold,
                "hold_to_val": hold_to_val,
                "abs_gap_to_hold_val": derived_abs_gap,
                "relative_gap_to_hold_val": relative_gap,
                "generalization_shift": synthetic_generalization,
                "risk_level": risk_level,
                "description": description,
            }
        )

    return metric_rows, summary_rows


def _resolve_bundle_path(run_dir: Path, value: str) -> Path | None:
    candidate = Path(value)
    if candidate.exists():
        return candidate

    if not candidate.is_absolute():
        alt = run_dir / candidate
        if alt.exists():
            return alt
        alt = Path.cwd() / candidate
        if alt.exists():
            return alt
        script_root = Path(__file__).resolve().parent.parent
        alt = script_root / candidate
        if alt.exists():
            return alt
        for ancestor in (run_dir.parent, run_dir.parent.parent):
            alt = ancestor / candidate
            if alt.exists():
                return alt
    return candidate


def _collect_training_time_series_rows(
    run_dir: Path,
    training_sections: Mapping[str, Mapping[str, Any]],
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []

    for run_section, section in sorted(training_sections.items()):
        artifact_name = section.get("artifact_name")
        if artifact_name not in TRAINING_RECORDS:
            continue
        status = section.get("status", "unknown")
        if status != "ok":
            continue
        source_file = section.get("source_file")
        if source_file is None:
            continue

        source_path = _resolve_bundle_path(run_dir, source_file)
        if not source_path.exists():
            continue

        if artifact_name in {"loss_point", "scalars"}:
            if artifact_name == "loss_point":
                pass

        if artifact_name == "loss":
            with source_path.open("r", encoding="utf-8", newline="") as fh:
                reader = csv.DictReader(fh)
                for row_idx, row in enumerate(reader):
                    if row is None:
                        continue
                    epoch = row.get("epoch", row_idx)
                    for metric_name, metric_raw in row.items():
                        if metric_name == "epoch":
                            continue
                        value = _safe_float(metric_raw)
                        rows.append(
                            {
                                "record_type": "loss_point",
                                "run_section": run_section,
                                "artifact_name": artifact_name,
                                "metric_name": metric_name,
                                "step_axis": "epoch",
                                "step": epoch,
                                "value": value,
                                "value_type": type(value).__name__ if value is not None else "missing",
                                "status": status,
                                "source_file": source_file,
                            }
                        )
            continue

        if artifact_name == "scalars":
            with source_path.open("r", encoding="utf-8", newline="") as fh:
                reader = csv.DictReader(fh)
                for row in reader:
                    if row is None:
                        continue
                    step = row.get("step")
                    tag = row.get("tag", "")
                    value = _safe_float(row.get("value"))
                    rows.append(
                        {
                            "record_type": "scalar_point",
                            "run_section": run_section,
                            "artifact_name": artifact_name,
                            "metric_name": str(tag),
                            "step_axis": "step",
                            "step": step,
                            "value": value,
                            "value_type": type(value).__name__ if value is not None else "missing",
                            "status": status,
                            "source_file": source_file,
                        }
                    )
            continue

        if artifact_name == "log":
            events = section.get("metrics", {}).get("events", [])
            if not isinstance(events, list):
                continue
            for event in events:
                if not isinstance(event, Mapping):
                    continue
                epoch = event.get("epoch")
                if epoch is None:
                    continue
                rows.append(
                    {
                        "record_type": "log_point",
                        "run_section": run_section,
                        "artifact_name": artifact_name,
                        "metric_name": "train_metric",
                        "step_axis": "epoch",
                        "step": epoch,
                        "value": _safe_float(event.get("train_metric")),
                        "value_type": "float",
                        "status": status,
                        "source_file": source_file,
                    }
                )
                rows.append(
                    {
                        "record_type": "log_point",
                        "run_section": run_section,
                        "artifact_name": artifact_name,
                        "metric_name": "val_metric",
                        "step_axis": "epoch",
                        "step": epoch,
                        "value": _safe_float(event.get("val_metric")),
                        "value_type": "float",
                        "status": status,
                        "source_file": source_file,
                    }
                )
    return rows


def _build_tooltips() -> dict[str, dict[str, str]]:
    tooltips = {
        metric_key: {
            "metric_id": metric_key,
            "metric_name": metric_name,
            "metric_family": family,
            "description": description,
            "lower_is_better": "true" if lower_is_better else "false",
        }
        for metric_key, family, metric_name, lower_is_better, description in STRUCTURE_METRICS
    }
    tooltips["comparison_summary__abs_gap_to_hold_val"] = {
        "metric_id": "comparison_summary__abs_gap_to_hold_val",
        "metric_name": "Abs gap from hold->val",
        "metric_family": "derived",
        "description": "Absolute difference between synth->val and hold->val. Lower suggests synthetic is close to real split drift.",
        "lower_is_better": "true",
    }
    tooltips["comparison_summary__relative_gap_to_hold_val"] = {
        "metric_id": "comparison_summary__relative_gap_to_hold_val",
        "metric_name": "Relative gap from hold->val",
        "metric_family": "derived",
        "description": "Absolute gap normalized by hold->val. Helps compare scale across metrics.",
        "lower_is_better": "true",
    }
    tooltips["comparison_summary__generalization_shift"] = {
        "metric_id": "comparison_summary__generalization_shift",
        "metric_name": "Generalization shift",
        "metric_family": "derived",
        "description": "How much synth->val differs from synth->hold beyond hold->val variation.",
        "lower_is_better": "true",
    }
    return tooltips


def _write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: _to_csv_value(row.get(field)) for field in fieldnames})


def _write_tooltips_csv(path: Path) -> dict[str, dict[str, str]]:
    tooltips = _build_tooltips()
    fieldnames = [
        "metric_id",
        "metric_name",
        "metric_family",
        "description",
        "lower_is_better",
    ]
    rows = [dict(item) for item in (tooltips.values())]
    _write_csv(path, rows, fieldnames)
    return tooltips


def _collect_summary_rows(
    run_dir: Path,
    metrics_summary_rows: list[dict[str, Any]],
    training_summary: Mapping[str, Any],
    include_metrics: bool,
    include_training: bool,
    tooltips: Mapping[str, Any],
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    rows.append(
        {
            "record_type": "run_info",
            "metric_family": "",
            "metric_key": "run_dir",
            "metric_label": "Run directory",
            "value": str(run_dir),
            "lower_is_better": "",
            "tooltip_id": "",
            "synth_to_val": "",
            "synth_to_hold": "",
            "hold_to_val": "",
            "abs_gap_to_hold_val": "",
            "relative_gap_to_hold_val": "",
            "generalization_shift": "",
            "risk_level": "",
            "description": "",
            "status": "ok",
        }
    )

    if include_metrics:
        for row in metrics_summary_rows:
            summary = dict(row)
            summary["record_type"] = "metrics_summary"
            rows.append(summary)

    if include_training:
        rows.append(
            {
                "record_type": "training_summary",
                "metric_family": "",
                "metric_key": "n_sections",
                "metric_label": "Training sections",
                "value": training_summary.get("n_sections"),
                "lower_is_better": "",
                "tooltip_id": "",
                "synth_to_val": "",
                "synth_to_hold": "",
                "hold_to_val": "",
                "abs_gap_to_hold_val": "",
                "relative_gap_to_hold_val": "",
                "generalization_shift": "",
                "risk_level": "",
                "description": "",
                "status": "",
            }
        )
        rows.append(
            {
                "record_type": "training_summary",
                "metric_family": "",
                "metric_key": "n_loss_rows",
                "metric_label": "Training loss rows",
                "value": training_summary.get("n_loss_rows"),
                "lower_is_better": "",
                "tooltip_id": "",
                "synth_to_val": "",
                "synth_to_hold": "",
                "hold_to_val": "",
                "abs_gap_to_hold_val": "",
                "relative_gap_to_hold_val": "",
                "generalization_shift": "",
                "risk_level": "",
                "description": "",
                "status": "",
            }
        )
        rows.append(
            {
                "record_type": "training_summary",
                "metric_family": "",
                "metric_key": "n_scalar_points",
                "metric_label": "Training scalar points",
                "value": training_summary.get("n_scalar_points"),
                "lower_is_better": "",
                "tooltip_id": "",
                "synth_to_val": "",
                "synth_to_hold": "",
                "hold_to_val": "",
                "abs_gap_to_hold_val": "",
                "relative_gap_to_hold_val": "",
                "generalization_shift": "",
                "risk_level": "",
                "description": "",
                "status": "",
            }
        )
        rows.append(
            {
                "record_type": "training_summary",
                "metric_family": "",
                "metric_key": "n_log_events",
                "metric_label": "Training log events",
                "value": training_summary.get("n_log_events"),
                "lower_is_better": "",
                "tooltip_id": "",
                "synth_to_val": "",
                "synth_to_hold": "",
                "hold_to_val": "",
                "abs_gap_to_hold_val": "",
                "relative_gap_to_hold_val": "",
                "generalization_shift": "",
                "risk_level": "",
                "description": "",
                "status": "",
            }
        )

    if include_metrics:
        rows.append(
            {
                "record_type": "metrics_available",
                "metric_family": "",
                "metric_key": "tooltip_count",
                "metric_label": "Metric tooltips",
                "value": len(tooltips),
                "lower_is_better": "",
                "tooltip_id": "",
                "synth_to_val": "",
                "synth_to_hold": "",
                "hold_to_val": "",
                "abs_gap_to_hold_val": "",
                "relative_gap_to_hold_val": "",
                "generalization_shift": "",
                "risk_level": "",
                "description": "",
                "status": "",
            }
        )

    return rows


def _build_comparison_plot(metric_summary: list[dict[str, Any]], out_path: Path) -> bool:
    if plt is None:
        return False
    by_family = defaultdict(list)
    for row in metric_summary:
        family = str(row.get("metric_family"))
        key = str(row.get("metric_key"))
        if not family or not key:
            continue
        by_family[family].append(row)
    if not by_family:
        return False

    fig, axes = None, None
    for family_idx, (family, rows) in enumerate(by_family.items()):
        if not rows:
            continue
        metrics = sorted([r["metric_key"] for r in rows])
        labels = list(dict.fromkeys(metrics))
        directions = [d for d, _ in COMPARE_DIRECTIONS]
        xs = range(len(labels))
        width = 0.2
        if fig is None:
            fig = plt.figure(figsize=(max(8, len(labels) * 0.8), 4 * len(by_family)))
            axes = fig.subplots(len(by_family), 1, squeeze=False)
        fam_rows = by_family[family]
        family_values: dict[str, list[float | None]] = {d: [] for d, _ in COMPARE_DIRECTIONS}
        for label in labels:
            for direction in directions:
                value = next(
                    (
                        row.get("value")
                        for row in fam_rows
                        if row.get("metric_key") == label and row.get("direction") == direction
                    ),
                    None,
                )
                if isinstance(value, str):
                    value = _safe_float(value)
                family_values[direction].append(value)

        axis = axes[family_idx][0] if axes is not None else None
        if axis is None:
            continue
        for offset_i, direction in enumerate(directions):
            y_values = [
                v if isinstance(v, (float, int)) else math.nan for v in family_values[direction]
            ]
            axis.bar([x + offset_i * width for x in xs], y_values, width=width, label=direction)
        axis.set_title(f"{family.upper()} structure comparisons")
        axis.set_xticks([x + width for x in xs])
        axis.set_xticklabels(labels, rotation=35, ha="right")
        axis.set_ylabel("value")
        axis.grid(True, alpha=0.2)
        axis.legend()

    if fig is None or axes is None:
        return False
    fig.tight_layout()
    fig.savefig(out_path)
    plt.close(fig)
    return True


def _build_leakage_plot(metric_summary: list[dict[str, Any]], out_path: Path) -> bool:
    if plt is None:
        return False
    points = []
    for row in metric_summary:
        metric_key = row.get("metric_key")
        if not metric_key:
            continue
        relative = row.get("relative_gap_to_hold_val")
        if not isinstance(relative, (int, float)):
            continue
        points.append((str(metric_key), float(relative), str(row.get("metric_family", ""))))

    if not points:
        return False

    labels = [p[0] for p in points]
    values = [p[1] for p in points]
    families = [p[2] for p in points]
    colors = ["#4c72b0" if f == "od" else "#dd8452" if f == "joint" else "#55a868" for f in families]

    fig, ax = plt.subplots(figsize=(max(8, len(points) * 0.35), 5))
    ax.bar(range(len(points)), values, color=colors)
    ax.set_xticks(range(len(points)))
    ax.set_xticklabels(labels, rotation=45, ha="right")
    ax.set_title("Relative deviation vs hold->val")
    ax.set_ylabel("abs(synth->val - hold->val) / hold->val")
    ax.axhline(0.1, color="#2ca02c", linestyle="--", alpha=0.8, label="0.10")
    ax.axhline(0.25, color="#d62728", linestyle="--", alpha=0.8, label="0.25")
    ax.grid(True, alpha=0.2)
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_path)
    plt.close(fig)
    return True


def _build_training_plot(training_rows: list[dict[str, Any]], out_path: Path) -> bool:
    if plt is None:
        return False
    if not training_rows:
        return False

    points_by_metric: dict[str, list[tuple[float, float, str]]] = defaultdict(list)
    for row in training_rows:
        metric_name = str(row.get("metric_name", ""))
        step = _safe_float(row.get("step"))
        value = row.get("value")
        if not metric_name or step is None or value is None:
            continue
        section = str(row.get("run_section"))
        points_by_metric[metric_name].append((float(step), float(value), section))

    if not points_by_metric:
        return False

    fig, ax = plt.subplots(figsize=(10, 6))
    for metric_name, points in points_by_metric.items():
        points.sort(key=lambda item: item[0])
        xs = [p[0] for p in points]
        ys = [p[1] for p in points]
        label = metric_name
        ax.plot(xs, ys, marker="o", markersize=2, label=label)
    ax.set_xlabel("step")
    ax.set_ylabel("metric value")
    ax.set_title("Training curves (all sections)")
    ax.grid(True, alpha=0.2)
    ax.legend(fontsize=8, loc="upper right")
    fig.tight_layout()
    fig.savefig(out_path)
    plt.close(fig)
    return True


def _render_html_report(
    output_path: Path,
    run_dir: Path,
    metrics_summary: list[dict[str, Any]],
    training_summary_rows: list[dict[str, Any]],
    generated_at: str,
    generated_files: Mapping[str, str],
    plot_files: Mapping[str, str],
    tooltips: Mapping[str, Mapping[str, str]],
) -> None:
    metric_rows = sorted(
        [row for row in metrics_summary if row.get("metric_key") not in {None, ""}],
        key=lambda item: (str(item.get("metric_family")), str(item.get("metric_key"))),
    )[:200]

    training_points = len(training_summary_rows)
    metric_points = len(metrics_summary)

    tooltip_cells = [
        f"<tr><td>{html.escape(str(row))}</td><td>{html.escape(str(desc))}</td><td>{'lower' if row.get('lower_is_better') else 'higher' if row.get('lower_is_better') == False else ''}</td></tr>"
        for row, desc in [(row, row.get("description", "")) for row in tooltips.values()]
    ]

    table_rows = []
    for row in metric_rows:
        table_rows.append(
            f"<tr><td>{html.escape(str(row.get('metric_key', '')))}</td>"
            f"<td>{html.escape(str(row.get('metric_label', '')))}</td>"
            f"<td>{html.escape(str(row.get('risk_level', '')))}</td>"
            f"<td>{html.escape(str(row.get('synth_to_val', '')))}</td>"
            f"<td>{html.escape(str(row.get('synth_to_hold', '')))}</td>"
            f"<td>{html.escape(str(row.get('hold_to_val', '')))}</td>"
            f"<td>{html.escape(str(row.get('relative_gap_to_hold_val', '')))}</td></tr>"
        )

    plot_thumbnails = []
    for name, rel in plot_files.items():
        if rel:
            plot_thumbnails.append(
                f"<h3>{html.escape(name)}</h3><img src=\"{html.escape(rel)}\" "
                "style=\"max-width: 100%; border: 1px solid #ddd; margin-bottom: 12px;\" />"
            )

    html_text = f"""<!DOCTYPE html>
<html>
<head>
  <meta charset=\"utf-8\" />
  <title>Run Export Analysis</title>
  <style>
    body {{font-family: Arial, sans-serif; margin: 24px; color: #111;}}
    table {{border-collapse: collapse; width: 100%; font-size: 12px;}}
    th, td {{border: 1px solid #ddd; padding: 6px;}}
    th {{background: #f5f5f5;}}
    h2 {{margin-top: 28px;}}
    .muted {{color: #666;}}
  </style>
</head>
<body>
  <h1>Run Export Analysis</h1>
  <p class=\"muted\">Run: {html.escape(str(run_dir))}</p>
  <p class=\"muted\">Generated at: {html.escape(generated_at)}</p>
  <h2>Artifacts</h2>
  <ul>
    <li>analysis_report.json</li>
    <li>analysis_summary.csv</li>
    <li>analysis_metrics_long.csv ({metric_points} rows)</li>
    <li>analysis_training_long.csv ({training_points} rows)</li>
    <li>analysis_tooltips.csv</li>
  </ul>
  <h2>Files</h2>
  <pre>{html.escape(json.dumps(generated_files, indent=2))}</pre>

  <h2>Metric comparison summary</h2>
  <table>
    <thead>
      <tr>
        <th>metric</th>
        <th>label</th>
        <th>risk</th>
        <th>synth->val</th>
        <th>synth->hold</th>
        <th>hold->val</th>
        <th>relative gap</th>
      </tr>
    </thead>
    <tbody>
      {''.join(table_rows)}
    </tbody>
  </table>

  <h2>Tooltips</h2>
  <table>
    <thead>
      <tr>
        <th>metric_id</th>
        <th>description</th>
        <th>preferred direction</th>
      </tr>
    </thead>
    <tbody>
      {''.join(tooltip_cells)}
    </tbody>
  </table>

  <h2>Generated plots</h2>
  {''.join(plot_thumbnails)}
</body>
</html>
"""
    output_path.write_text(html_text, encoding="utf-8")


def analyze_run_exports(
    *,
    run_dir: Path,
    metrics_export_json: Path | None = None,
    training_export_json: Path | None = None,
    output_dir: Path | None = None,
    analyze_metrics: bool = True,
    analyze_training: bool = True,
    strict: bool = False,
    no_plots: bool = False,
) -> dict[str, Any]:
    run_dir = Path(run_dir)
    output_dir = Path(output_dir) if output_dir is not None else run_dir / ANALYSIS_DIR_NAME
    output_dir.mkdir(parents=True, exist_ok=True)
    figures_dir = output_dir / OUTPUT_FIG_DIR
    figures_dir.mkdir(parents=True, exist_ok=True)

    output_json = output_dir / OUTPUT_JSON
    summary_csv = output_dir / OUTPUT_SUMMARY_CSV
    metrics_csv = output_dir / OUTPUT_METRICS_CSV
    training_csv = output_dir / OUTPUT_TRAINING_CSV
    tooltips_csv = output_dir / OUTPUT_TOOLTIPS_CSV
    html_report = output_dir / OUTPUT_HTML

    if metrics_export_json is None:
        metrics_export_json = run_dir / "metrics" / "metrics_export.json"
    if training_export_json is None:
        training_export_json = run_dir / "training" / "training_export.json"

    metrics_bundle: Mapping[str, Any] | None = None
    training_bundle: Mapping[str, Any] | None = None
    metrics_sections: Mapping[str, Mapping[str, Any]] = {}
    training_sections: Mapping[str, Mapping[str, Any]] = {}
    metrics_generated_at = None
    training_generated_at = None

    if analyze_metrics:
        if not metrics_export_json.exists():
            msg = f"missing metrics export: {metrics_export_json}"
            if strict:
                raise FileNotFoundError(msg)
            print(f"[analyze] warning: {msg}")
        else:
            metrics_bundle = _read_json(metrics_export_json)
            metrics_sections = _flatten_sections(metrics_bundle)
            metrics_generated_at = metrics_bundle.get("generated_at")
    if analyze_training:
        if not training_export_json.exists():
            msg = f"missing training export: {training_export_json}"
            if strict:
                raise FileNotFoundError(msg)
            print(f"[analyze] warning: {msg}")
        else:
            training_bundle = _read_json(training_export_json)
            training_sections = _flatten_sections(training_bundle)
            training_generated_at = training_bundle.get("generated_at")

    metrics_rows: list[dict[str, Any]] = []
    metric_summary_rows: list[dict[str, Any]] = []
    training_rows: list[dict[str, Any]] = []
    if analyze_metrics and metrics_bundle is not None:
        metrics_rows, metric_summary_rows = _collect_metric_comparison_rows(metrics_sections)
        _write_csv(metrics_csv, metrics_rows, [
            "record_type",
            "metric_family",
            "metric_key",
            "metric_label",
            "direction",
            "run_section",
            "value",
            "value_type",
            "lower_is_better",
            "status",
            "source_file",
            "tooltip_id",
            "description",
        ])

    if analyze_training and training_bundle is not None:
        training_rows = _collect_training_time_series_rows(run_dir=run_dir, training_sections=training_sections)
        if training_rows:
            _write_csv(training_csv, training_rows, [
                "record_type",
                "run_section",
                "artifact_name",
                "metric_name",
                "step_axis",
                "step",
                "value",
                "value_type",
                "status",
                "source_file",
            ])
        else:
            # keep an empty placeholder file for deterministic tooling
            _write_csv(training_csv, [], [
                "record_type",
                "run_section",
                "artifact_name",
                "metric_name",
                "step_axis",
                "step",
                "value",
                "value_type",
                "status",
                "source_file",
            ])

    tooltips = _build_tooltips()
    _write_tooltips_csv(tooltips_csv)

    training_summary = (
        dict(training_bundle.get("summary", {})) if isinstance(training_bundle, Mapping) else {}
    )
    summary_rows = _collect_summary_rows(
        run_dir=run_dir,
        metrics_summary_rows=metric_summary_rows,
        training_summary=training_summary,
        include_metrics=analyze_metrics and bool(metrics_rows),
        include_training=analyze_training and bool(training_summary),
        tooltips=tooltips,
    )
    _write_csv(summary_csv, summary_rows, [
        "record_type",
        "metric_family",
        "metric_key",
        "metric_label",
        "value",
        "lower_is_better",
        "tooltip_id",
        "synth_to_val",
        "synth_to_hold",
        "hold_to_val",
        "abs_gap_to_hold_val",
        "relative_gap_to_hold_val",
        "generalization_shift",
        "risk_level",
        "description",
        "status",
    ])

    plot_files: dict[str, str] = {}
    if not no_plots:
        comparison_plot = figures_dir / OUTPUT_FIG_COMPARISON
        if _build_comparison_plot(metric_summary_rows, comparison_plot):
            plot_files["comparison_plot"] = str(comparison_plot.relative_to(output_dir))
        leakage_plot = figures_dir / OUTPUT_FIG_LEAKAGE
        if _build_leakage_plot(metric_summary_rows, leakage_plot):
            plot_files["leakage_plot"] = str(leakage_plot.relative_to(output_dir))
        training_plot = figures_dir / OUTPUT_FIG_TRAINING
        if _build_training_plot(training_rows, training_plot):
            plot_files["training_plot"] = str(training_plot.relative_to(output_dir))

    generated_at = datetime.now(timezone.utc).isoformat()
    report_payload: dict[str, Any] = {
        "schema_version": ANALYSIS_SCHEMA_VERSION,
        "generated_at": generated_at,
        "run_dir": str(run_dir),
        "input": {
            "run_dir": str(run_dir),
            "metrics_export_json": str(metrics_export_json),
            "training_export_json": str(training_export_json),
            "analyze_metrics": analyze_metrics,
            "analyze_training": analyze_training,
            "strict": strict,
            "no_plots": no_plots,
            "metrics_export_generated_at": metrics_generated_at,
            "training_export_generated_at": training_generated_at,
        },
        "summary": {
            "generated_rows": {
                "metrics_long": len(metrics_rows),
                "training_long": len(training_rows),
                "tooltips": len(tooltips),
            },
            "risk_count": {
                "low": sum(
                    1 for row in metric_summary_rows if row.get("risk_level") == "low"
                ),
                "medium": sum(
                    1 for row in metric_summary_rows if row.get("risk_level") == "medium"
                ),
                "high": sum(
                    1 for row in metric_summary_rows if row.get("risk_level") == "high"
                ),
                "unknown": sum(
                    1 for row in metric_summary_rows if row.get("risk_level") == "unknown"
                ),
            },
        },
        "metric_comparisons": metric_summary_rows,
        "training_summary": training_summary,
        "generated_files": {
            "output_dir": str(output_dir),
            "analysis_report_json": str(output_json),
            "analysis_summary_csv": str(summary_csv),
            "analysis_metrics_long_csv": str(metrics_csv),
            "analysis_training_long_csv": str(training_csv),
            "analysis_tooltips_csv": str(tooltips_csv),
            "analysis_report_html": str(html_report),
            "figures_dir": str(figures_dir),
            **{name: str(path) for name, path in plot_files.items()},
        },
    }
    output_json.write_text(json.dumps(report_payload, indent=2, ensure_ascii=False), encoding="utf-8")

    _render_html_report(
        output_path=html_report,
        run_dir=run_dir,
        metrics_summary=metric_summary_rows,
        training_summary_rows=training_rows,
        generated_at=generated_at,
        generated_files=report_payload["generated_files"],
        plot_files=plot_files,
        tooltips=tooltips,
    )

    return report_payload


def _resolve_bool(raw: str | None) -> bool:
    if raw is None:
        return True
    if raw.lower() in {"1", "true", "yes", "y", "on"}:
        return True
    if raw.lower() in {"0", "false", "no", "n", "off"}:
        return False
    raise argparse.ArgumentTypeError(f"invalid boolean value: {raw}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate analysis and plots from run export artifacts.")
    parser.add_argument("--run-dir", type=Path, required=True, help="Run directory with metrics/training exports.")
    parser.add_argument("--metrics-export-json", type=Path, default=None, help="Path to metrics_export.json.")
    parser.add_argument("--training-export-json", type=Path, default=None, help="Path to training_export.json.")
    parser.add_argument("--output-dir", type=Path, default=None, help="Output directory for analysis artifacts.")
    parser.add_argument("--analysis-dir", type=Path, default=None, help="Alias for --output-dir.")
    parser.add_argument("--strict", action="store_true", help="Fail if any requested export artifact is missing.")
    parser.add_argument("--analyze-metrics", type=_resolve_bool, default=True, help="Analyze metric export (true/false).")
    parser.add_argument("--analyze-training", type=_resolve_bool, default=True, help="Analyze training export (true/false).")
    parser.add_argument("--no-plots", action="store_true", help="Do not render PNG plots.")
    args = parser.parse_args()

    output_dir = args.output_dir
    if output_dir is None and args.analysis_dir is not None:
        output_dir = args.analysis_dir

    analyze_run_exports(
        run_dir=args.run_dir,
        metrics_export_json=args.metrics_export_json,
        training_export_json=args.training_export_json,
        output_dir=output_dir,
        analyze_metrics=args.analyze_metrics if isinstance(args.analyze_metrics, bool) else True,
        analyze_training=args.analyze_training if isinstance(args.analyze_training, bool) else True,
        strict=args.strict,
        no_plots=args.no_plots,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
