from __future__ import annotations

import argparse
import csv
import html
import json
import math
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt  # type: ignore
except Exception:  # pragma: no cover - optional dependency
    plt = None


PLOT_LIB_AVAILABLE = plt is not None


ANALYSIS_SCHEMA_VERSION = "1.0.0"
ANALYSIS_DIR_NAME = "analysis"

OUTPUT_JSON = "analysis_report.json"
OUTPUT_SUMMARY_CSV = "analysis_summary.csv"
OUTPUT_METRICS_CSV = "analysis_metrics_long.csv"
OUTPUT_TRAINING_CSV = "analysis_training_long.csv"
OUTPUT_TOOLTIPS_CSV = "analysis_tooltips.csv"
OUTPUT_HTML = "analysis_report.html"
OUTPUT_FIG_DIR = "figs"
OUTPUT_FIG_COMPARISON = "comparison_metrics.png"
OUTPUT_FIG_LEAKAGE = "comparison_leakage.png"
OUTPUT_FIG_TRAINING = "training_curves.png"


STRUCTURE_METRICS = [
    ("od_jsd", "od", "OD JSD", True, "Distribution mismatch between OD marginals."),
    ("od_chi2", "od", "OD Chi²", True, "OD chi-square divergence for synthetic vs real."),
    ("od_coverage_real", "od", "OD coverage (real)", False, "Real OD support coverage (higher is better)."),
    ("od_coverage_synth", "od", "OD coverage (synth)", False, "Synthetic OD support coverage (higher is better)."),
    (
        "od_unique_real",
        "od",
        "OD unique modes (real)",
        False,
        "Unique OD modes observed in the real distribution.",
    ),
    (
        "od_unique_synth",
        "od",
        "OD unique modes (synth)",
        False,
        "Unique OD modes generated by synthetic samples.",
    ),
    ("joint_jsd", "joint", "Joint JSD", True, "Joint OD+time distribution mismatch."),
    ("joint_chi2", "joint", "Joint Chi²", True, "Joint OD+time chi-square divergence."),
    (
        "joint_coverage_real",
        "joint",
        "Joint coverage (real)",
        False,
        "Real joint support coverage (higher is better).",
    ),
    (
        "joint_coverage_synth",
        "joint",
        "Joint coverage (synth)",
        False,
        "Synthetic joint support coverage (higher is better).",
    ),
    (
        "joint_unique_real",
        "joint",
        "Joint unique modes (real)",
        False,
        "Unique OD+time mode count for real data.",
    ),
    (
        "joint_unique_synth",
        "joint",
        "Joint unique modes (synth)",
        False,
        "Unique OD+time mode count for synthetic data.",
    ),
    (
        "joint_mode_dropping_ratio",
        "joint",
        "Joint mode dropping ratio",
        True,
        "Portion of real joint modes that disappear in synthetic.",
    ),
    (
        "joint_invalid_ratio",
        "joint",
        "Joint invalid ratio",
        True,
        "Portion of invalid OD pairs in synthetic samples.",
    ),
]


KEY_ALIASES = {
    "od_coverage_real": (
        "od_coverage_real",
        "od_cov_real",
        "cov_real",
        "coverage_real",
    ),
    "od_coverage_synth": (
        "od_coverage_synth",
        "od_cov_syn",
        "cov_synth",
        "coverage_synth",
    ),
    "joint_coverage_real": (
        "joint_coverage_real",
        "joint_cov_real",
        "joint_coverage",
    ),
    "joint_coverage_synth": (
        "joint_coverage_synth",
        "joint_cov_synth",
        "joint_coverage_synth_real",
    ),
    "od_unique_real": ("od_unique_real", "od_unique"),
    "od_unique_synth": ("od_unique_synth",),
    "joint_unique_real": ("joint_unique_real",),
    "joint_unique_synth": ("joint_unique_synth",),
    "joint_invalid_ratio": ("joint_invalid_ratio",),
}


COMPARE_DIRECTIONS = [
    ("synth->val", "strategy_val"),
    ("synth->hold", "strategy_hold"),
    ("hold->val", "strategy_hold_vs_val_real"),
]


TRAINING_RECORDS = ("loss", "scalars", "log")


def _safe_float(value: Any) -> float | None:
    if value is None:
        return None
    if isinstance(value, bool):
        return float(value)
    if isinstance(value, (int, float)):
        return float(value)
    try:
        parsed = float(str(value).strip())
    except (TypeError, ValueError):
        return None
    if math.isfinite(parsed):
        return parsed
    return None


def _read_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as fh:
        payload = json.load(fh)
    if isinstance(payload, Mapping):
        return dict(payload)
    raise TypeError(f"invalid JSON payload in {path}: expected object")


def _to_csv_value(value: Any) -> str | int | float | bool:
    if value is None:
        return ""
    if isinstance(value, bool):
        return value
    if isinstance(value, float):
        return value if not math.isnan(value) else ""
    if isinstance(value, (int, str)):
        return value
    return str(value)


def _to_html_value(value: Any, precision: int = 6) -> str:
    if value is None or value == "":
        return "&ndash;"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return f"{value}"
    if isinstance(value, float):
        if not math.isfinite(value):
            return "&ndash;"
        if value == 0:
            return "0"
        return f"{value:.{precision}f}".rstrip("0").rstrip(".")
    return html.escape(str(value))


def _to_html_label(value: Any) -> str:
    if value is None or value == "":
        return "&ndash;"
    if value is True:
        return "yes"
    if value is False:
        return "no"
    return html.escape(str(value))


def _risk_badge_class(level: str) -> str:
    if level == "low":
        return "risk-low"
    if level == "medium":
        return "risk-medium"
    if level == "high":
        return "risk-high"
    return "risk-unknown"


def _metric_preferred_direction(lower_is_better: bool) -> str:
    return "smaller is better" if lower_is_better else "larger is better"


def _safe_float_sort(value: Any) -> float:
    if isinstance(value, bool):
        return float(value)
    if isinstance(value, (int, float)) and math.isfinite(float(value)):
        return float(value)
    return float("inf")


def _metric_aliases(key: str) -> tuple[str, ...]:
    return KEY_ALIASES.get(key, (key,))


def _metric_from_section(section: Mapping[str, Any], metric_key: str) -> float | None:
    metrics = section.get("metrics", {})
    if not isinstance(metrics, Mapping):
        return None
    for candidate in _metric_aliases(metric_key):
        value = _safe_float(metrics.get(candidate))
        if value is not None:
            return value
    return None


def _flatten_sections(bundle: Mapping[str, Any]) -> Mapping[str, Mapping[str, Any]]:
    sections = bundle.get("sections")
    if isinstance(sections, Mapping):
        return {str(k): dict(v) for k, v in sections.items() if isinstance(v, Mapping)}
    return {}


def _collect_metric_comparison_rows(
    metrics_sections: Mapping[str, Mapping[str, Any]],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    metric_rows: list[dict[str, Any]] = []
    summary_rows: list[dict[str, Any]] = []

    for metric_key, family, metric_label, lower_is_better, description in STRUCTURE_METRICS:
        direction_values: dict[str, float | None] = {}
        for direction, section_name in COMPARE_DIRECTIONS:
            section = metrics_sections.get(section_name, {})
            status = section.get("status", "missing")
            source_file = section.get("source_file")
            value = _metric_from_section(section, metric_key)
            direction_values[direction] = value
            metric_rows.append(
                {
                    "record_type": "metric_point",
                    "metric_family": family,
                    "metric_key": metric_key,
                    "metric_label": metric_label,
                    "direction": direction,
                    "run_section": section_name,
                    "value": value,
                    "value_type": type(value).__name__ if value is not None else "missing",
                    "lower_is_better": lower_is_better,
                    "status": status,
                    "source_file": source_file if source_file is not None else "",
                    "tooltip_id": metric_key,
                    "description": description,
                }
            )

        synth_to_val = direction_values.get("synth->val")
        synth_to_hold = direction_values.get("synth->hold")
        hold_to_val = direction_values.get("hold->val")

        # Derived indicators:
        # 1) How much additional variation appears in synth->val relative to natural hold->val variation.
        # 2) Whether the synthetic distribution drift from hold to val is larger than synthetic->hold.
        derived_abs_gap = None
        relative_gap = None
        synthetic_generalization = None
        risk_level = "unknown"
        if (
            synth_to_val is not None
            and hold_to_val is not None
        ):
            derived_abs_gap = abs(synth_to_val - hold_to_val)
            if hold_to_val != 0:
                relative_gap = derived_abs_gap / abs(hold_to_val)
            if lower_is_better:
                if relative_gap is None:
                    risk_level = "unknown"
                elif relative_gap <= 0.10:
                    risk_level = "low"
                elif relative_gap <= 0.25:
                    risk_level = "medium"
                else:
                    risk_level = "high"
            else:
                if relative_gap is None:
                    risk_level = "unknown"
                elif relative_gap <= 0.10:
                    risk_level = "low"
                elif relative_gap <= 0.25:
                    risk_level = "medium"
                else:
                    risk_level = "high"

        if (
            synth_to_val is not None
            and synth_to_hold is not None
            and hold_to_val is not None
        ):
            synthetic_generalization = (synth_to_val - hold_to_val) - (synth_to_hold - hold_to_val)

        summary_rows.append(
            {
                "record_type": "comparison_summary",
                "metric_family": family,
                "metric_key": metric_key,
                "metric_label": metric_label,
                "lower_is_better": lower_is_better,
                "tooltip_id": metric_key,
                "synth_to_val": synth_to_val,
                "synth_to_hold": synth_to_hold,
                "hold_to_val": hold_to_val,
                "abs_gap_to_hold_val": derived_abs_gap,
                "relative_gap_to_hold_val": relative_gap,
                "generalization_shift": synthetic_generalization,
                "risk_level": risk_level,
                "description": description,
            }
        )

    return metric_rows, summary_rows


def _resolve_bundle_path(run_dir: Path, value: str) -> Path | None:
    candidate = Path(value)
    if candidate.exists():
        return candidate

    if not candidate.is_absolute():
        alt = run_dir / candidate
        if alt.exists():
            return alt
        alt = Path.cwd() / candidate
        if alt.exists():
            return alt
        script_root = Path(__file__).resolve().parent.parent
        alt = script_root / candidate
        if alt.exists():
            return alt
        for ancestor in (run_dir.parent, run_dir.parent.parent):
            alt = ancestor / candidate
            if alt.exists():
                return alt
    return candidate


def _collect_training_time_series_rows(
    run_dir: Path,
    training_sections: Mapping[str, Mapping[str, Any]],
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []

    for run_section, section in sorted(training_sections.items()):
        artifact_name = section.get("artifact_name")
        if artifact_name not in TRAINING_RECORDS:
            continue
        status = section.get("status", "unknown")
        if status != "ok":
            continue
        source_file = section.get("source_file")
        if source_file is None:
            continue

        source_path = _resolve_bundle_path(run_dir, source_file)
        if not source_path.exists():
            continue

        if artifact_name in {"loss_point", "scalars"}:
            if artifact_name == "loss_point":
                pass

        if artifact_name == "loss":
            with source_path.open("r", encoding="utf-8", newline="") as fh:
                reader = csv.DictReader(fh)
                for row_idx, row in enumerate(reader):
                    if row is None:
                        continue
                    epoch = row.get("epoch", row_idx)
                    for metric_name, metric_raw in row.items():
                        if metric_name == "epoch":
                            continue
                        value = _safe_float(metric_raw)
                        rows.append(
                            {
                                "record_type": "loss_point",
                                "run_section": run_section,
                                "artifact_name": artifact_name,
                                "metric_name": metric_name,
                                "step_axis": "epoch",
                                "step": epoch,
                                "value": value,
                                "value_type": type(value).__name__ if value is not None else "missing",
                                "status": status,
                                "source_file": source_file,
                            }
                        )
            continue

        if artifact_name == "scalars":
            with source_path.open("r", encoding="utf-8", newline="") as fh:
                reader = csv.DictReader(fh)
                for row in reader:
                    if row is None:
                        continue
                    step = row.get("step")
                    tag = row.get("tag", "")
                    value = _safe_float(row.get("value"))
                    rows.append(
                        {
                            "record_type": "scalar_point",
                            "run_section": run_section,
                            "artifact_name": artifact_name,
                            "metric_name": str(tag),
                            "step_axis": "step",
                            "step": step,
                            "value": value,
                            "value_type": type(value).__name__ if value is not None else "missing",
                            "status": status,
                            "source_file": source_file,
                        }
                    )
            continue

        if artifact_name == "log":
            events = section.get("metrics", {}).get("events", [])
            if not isinstance(events, list):
                continue
            for event in events:
                if not isinstance(event, Mapping):
                    continue
                epoch = event.get("epoch")
                if epoch is None:
                    continue
                rows.append(
                    {
                        "record_type": "log_point",
                        "run_section": run_section,
                        "artifact_name": artifact_name,
                        "metric_name": "train_metric",
                        "step_axis": "epoch",
                        "step": epoch,
                        "value": _safe_float(event.get("train_metric")),
                        "value_type": "float",
                        "status": status,
                        "source_file": source_file,
                    }
                )
                rows.append(
                    {
                        "record_type": "log_point",
                        "run_section": run_section,
                        "artifact_name": artifact_name,
                        "metric_name": "val_metric",
                        "step_axis": "epoch",
                        "step": epoch,
                        "value": _safe_float(event.get("val_metric")),
                        "value_type": "float",
                        "status": status,
                        "source_file": source_file,
                    }
                )
    return rows


def _build_tooltips() -> dict[str, dict[str, str]]:
    tooltips = {
        metric_key: {
            "metric_id": metric_key,
            "metric_name": metric_name,
            "metric_family": family,
            "description": description,
            "preferred_direction": _metric_preferred_direction(lower_is_better),
            "lower_is_better": "true" if lower_is_better else "false",
        }
        for metric_key, family, metric_name, lower_is_better, description in STRUCTURE_METRICS
    }
    tooltips["comparison_summary__abs_gap_to_hold_val"] = {
        "metric_id": "comparison_summary__abs_gap_to_hold_val",
        "metric_name": "Abs gap from hold->val",
        "metric_family": "derived",
        "preferred_direction": "smaller is better",
        "description": "Absolute difference between synth->val and hold->val. Lower suggests synthetic is close to real split drift.",
        "lower_is_better": "true",
    }
    tooltips["comparison_summary__relative_gap_to_hold_val"] = {
        "metric_id": "comparison_summary__relative_gap_to_hold_val",
        "metric_name": "Relative gap from hold->val",
        "metric_family": "derived",
        "preferred_direction": "smaller is better",
        "description": "Absolute gap normalized by hold->val. Helps compare scale across metrics.",
        "lower_is_better": "true",
    }
    tooltips["comparison_summary__generalization_shift"] = {
        "metric_id": "comparison_summary__generalization_shift",
        "metric_name": "Generalization shift",
        "metric_family": "derived",
        "preferred_direction": "smaller is better",
        "description": "How much synth->val differs from synth->hold beyond hold->val variation.",
        "lower_is_better": "true",
    }
    return tooltips


def _write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: _to_csv_value(row.get(field)) for field in fieldnames})


def _write_tooltips_csv(path: Path) -> dict[str, dict[str, str]]:
    tooltips = _build_tooltips()
    fieldnames = [
        "metric_id",
        "metric_name",
        "metric_family",
        "description",
        "preferred_direction",
        "lower_is_better",
    ]
    rows = [dict(item) for item in (tooltips.values())]
    _write_csv(path, rows, fieldnames)
    return tooltips


def _collect_summary_rows(
    run_dir: Path,
    metrics_summary_rows: list[dict[str, Any]],
    training_summary: Mapping[str, Any],
    include_metrics: bool,
    include_training: bool,
    tooltips: Mapping[str, Any],
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    rows.append(
        {
            "record_type": "run_info",
            "metric_family": "",
            "metric_key": "run_dir",
            "metric_label": "Run directory",
            "value": str(run_dir),
            "lower_is_better": "",
            "tooltip_id": "",
            "synth_to_val": "",
            "synth_to_hold": "",
            "hold_to_val": "",
            "abs_gap_to_hold_val": "",
            "relative_gap_to_hold_val": "",
            "generalization_shift": "",
            "risk_level": "",
            "description": "",
            "status": "ok",
        }
    )

    if include_metrics:
        for row in metrics_summary_rows:
            summary = dict(row)
            summary["record_type"] = "metrics_summary"
            rows.append(summary)

    if include_training:
        rows.append(
            {
                "record_type": "training_summary",
                "metric_family": "",
                "metric_key": "n_sections",
                "metric_label": "Training sections",
                "value": training_summary.get("n_sections"),
                "lower_is_better": "",
                "tooltip_id": "",
                "synth_to_val": "",
                "synth_to_hold": "",
                "hold_to_val": "",
                "abs_gap_to_hold_val": "",
                "relative_gap_to_hold_val": "",
                "generalization_shift": "",
                "risk_level": "",
                "description": "",
                "status": "",
            }
        )
        rows.append(
            {
                "record_type": "training_summary",
                "metric_family": "",
                "metric_key": "n_loss_rows",
                "metric_label": "Training loss rows",
                "value": training_summary.get("n_loss_rows"),
                "lower_is_better": "",
                "tooltip_id": "",
                "synth_to_val": "",
                "synth_to_hold": "",
                "hold_to_val": "",
                "abs_gap_to_hold_val": "",
                "relative_gap_to_hold_val": "",
                "generalization_shift": "",
                "risk_level": "",
                "description": "",
                "status": "",
            }
        )
        rows.append(
            {
                "record_type": "training_summary",
                "metric_family": "",
                "metric_key": "n_scalar_points",
                "metric_label": "Training scalar points",
                "value": training_summary.get("n_scalar_points"),
                "lower_is_better": "",
                "tooltip_id": "",
                "synth_to_val": "",
                "synth_to_hold": "",
                "hold_to_val": "",
                "abs_gap_to_hold_val": "",
                "relative_gap_to_hold_val": "",
                "generalization_shift": "",
                "risk_level": "",
                "description": "",
                "status": "",
            }
        )
        rows.append(
            {
                "record_type": "training_summary",
                "metric_family": "",
                "metric_key": "n_log_events",
                "metric_label": "Training log events",
                "value": training_summary.get("n_log_events"),
                "lower_is_better": "",
                "tooltip_id": "",
                "synth_to_val": "",
                "synth_to_hold": "",
                "hold_to_val": "",
                "abs_gap_to_hold_val": "",
                "relative_gap_to_hold_val": "",
                "generalization_shift": "",
                "risk_level": "",
                "description": "",
                "status": "",
            }
        )

    if include_metrics:
        rows.append(
            {
                "record_type": "metrics_available",
                "metric_family": "",
                "metric_key": "tooltip_count",
                "metric_label": "Metric tooltips",
                "value": len(tooltips),
                "lower_is_better": "",
                "tooltip_id": "",
                "synth_to_val": "",
                "synth_to_hold": "",
                "hold_to_val": "",
                "abs_gap_to_hold_val": "",
                "relative_gap_to_hold_val": "",
                "generalization_shift": "",
                "risk_level": "",
                "description": "",
                "status": "",
            }
        )

    return rows


def _build_comparison_plot(
    metric_summary: list[dict[str, Any]], out_path: Path
) -> tuple[bool, str]:
    if plt is None:
        return False, "matplotlib_not_available"
    by_family = defaultdict(list)
    for row in metric_summary:
        family = str(row.get("metric_family"))
        key = str(row.get("metric_key"))
        if not family or not key:
            continue
        by_family[family].append(row)
    if not by_family:
        return False, "no_family_rows"

    try:
        fig, axes = None, None
        for family_idx, (family, rows) in enumerate(by_family.items()):
            if not rows:
                continue
            metrics = sorted([r["metric_key"] for r in rows])
            labels = list(dict.fromkeys(metrics))
            directions = [d for d, _ in COMPARE_DIRECTIONS]
            xs = range(len(labels))
            width = 0.2
            if fig is None:
                fig = plt.figure(figsize=(max(8, len(labels) * 0.8), 4 * len(by_family)))
                axes = fig.subplots(len(by_family), 1, squeeze=False)
            fam_rows = by_family[family]
            family_values: dict[str, list[float | None]] = {d: [] for d, _ in COMPARE_DIRECTIONS}
            for label in labels:
                for direction in directions:
                    value = next(
                        (
                            row.get("value")
                            for row in fam_rows
                            if row.get("metric_key") == label and row.get("direction") == direction
                        ),
                        None,
                    )
                    if isinstance(value, str):
                        value = _safe_float(value)
                    family_values[direction].append(value)

            axis = axes[family_idx][0] if axes is not None else None
            if axis is None:
                continue
            for offset_i, direction in enumerate(directions):
                y_values = [
                    v if isinstance(v, (float, int)) else math.nan for v in family_values[direction]
                ]
                axis.bar([x + offset_i * width for x in xs], y_values, width=width, label=direction)
            axis.set_title(f"{family.upper()} structure comparisons")
            axis.set_xticks([x + width for x in xs])
            axis.set_xticklabels(labels, rotation=35, ha="right")
            axis.set_ylabel("value")
            axis.grid(True, alpha=0.2)
            axis.legend()

        if fig is None or axes is None:
            return False, "empty_plot"

        fig.tight_layout()
        fig.savefig(out_path)
        plt.close(fig)
        return True, "generated"
    except Exception as exc:  # pragma: no cover - runtime safety
        return False, f"plot_error:{exc}"


def _build_leakage_plot(
    metric_summary: list[dict[str, Any]], out_path: Path
) -> tuple[bool, str]:
    if plt is None:
        return False, "matplotlib_not_available"
    points = []
    for row in metric_summary:
        metric_key = row.get("metric_key")
        if not metric_key:
            continue
        relative = row.get("relative_gap_to_hold_val")
        if not isinstance(relative, (int, float)):
            continue
        points.append((str(metric_key), float(relative), str(row.get("metric_family", ""))))

    if not points:
        return False, "no_relative_gaps"

    try:
        labels = [p[0] for p in points]
        values = [p[1] for p in points]
        families = [p[2] for p in points]
        colors = [
            "#4c72b0" if f == "od" else "#dd8452" if f == "joint" else "#55a868"
            for f in families
        ]

        fig, ax = plt.subplots(figsize=(max(8, len(points) * 0.35), 5))
        ax.bar(range(len(points)), values, color=colors)
        ax.set_xticks(range(len(points)))
        ax.set_xticklabels(labels, rotation=45, ha="right")
        ax.set_title("Relative deviation vs hold->val")
        ax.set_ylabel("abs(synth->val - hold->val) / hold->val")
        ax.axhline(0.1, color="#2ca02c", linestyle="--", alpha=0.8, label="0.10")
        ax.axhline(0.25, color="#d62728", linestyle="--", alpha=0.8, label="0.25")
        ax.grid(True, alpha=0.2)
        ax.legend()
        fig.tight_layout()
        fig.savefig(out_path)
        plt.close(fig)
        return True, "generated"
    except Exception as exc:  # pragma: no cover - runtime safety
        return False, f"plot_error:{exc}"


def _build_training_plot(
    training_rows: list[dict[str, Any]], out_path: Path
) -> tuple[bool, str]:
    if plt is None:
        return False, "matplotlib_not_available"
    if not training_rows:
        return False, "no_training_rows"

    try:
        points_by_metric: dict[str, list[tuple[float, float, str]]] = defaultdict(list)
        for row in training_rows:
            metric_name = str(row.get("metric_name", ""))
            step = _safe_float(row.get("step"))
            value = row.get("value")
            if not metric_name or step is None or value is None:
                continue
            section = str(row.get("run_section"))
            points_by_metric[metric_name].append((float(step), float(value), section))

        if not points_by_metric:
            return False, "no_plottable_training_rows"

        fig, ax = plt.subplots(figsize=(10, 6))
        for metric_name, points in points_by_metric.items():
            points.sort(key=lambda item: item[0])
            xs = [p[0] for p in points]
            ys = [p[1] for p in points]
            label = metric_name
            ax.plot(xs, ys, marker="o", markersize=2, label=label)
        ax.set_xlabel("step")
        ax.set_ylabel("metric value")
        ax.set_title("Training curves (all sections)")
        ax.grid(True, alpha=0.2)
        ax.legend(fontsize=8, loc="upper right")
        fig.tight_layout()
        fig.savefig(out_path)
        plt.close(fig)
        return True, "generated"
    except Exception as exc:  # pragma: no cover - runtime safety
        return False, f"plot_error:{exc}"


def _render_html_report_legacy(
    output_path: Path,
    run_dir: Path,
    metrics_summary: list[dict[str, Any]],
    training_summary_rows: list[dict[str, Any]],
    generated_at: str,
    generated_files: Mapping[str, str],
    plot_files: Mapping[str, str],
    tooltips: Mapping[str, Mapping[str, str]],
) -> None:
    metric_rows = sorted(
        [row for row in metrics_summary if row.get("metric_key") not in {None, ""}],
        key=lambda item: (str(item.get("metric_family")), str(item.get("metric_key"))),
    )[:200]

    training_points = len(training_summary_rows)
    metric_points = len(metrics_summary)

    tooltip_cells = [
        f"<tr><td>{html.escape(str(row))}</td><td>{html.escape(str(desc))}</td><td>{'lower' if row.get('lower_is_better') else 'higher' if row.get('lower_is_better') == False else ''}</td></tr>"
        for row, desc in [(row, row.get("description", "")) for row in tooltips.values()]
    ]

    table_rows = []
    for row in metric_rows:
        table_rows.append(
            f"<tr><td>{html.escape(str(row.get('metric_key', '')))}</td>"
            f"<td>{html.escape(str(row.get('metric_label', '')))}</td>"
            f"<td>{html.escape(str(row.get('risk_level', '')))}</td>"
            f"<td>{html.escape(str(row.get('synth_to_val', '')))}</td>"
            f"<td>{html.escape(str(row.get('synth_to_hold', '')))}</td>"
            f"<td>{html.escape(str(row.get('hold_to_val', '')))}</td>"
            f"<td>{html.escape(str(row.get('relative_gap_to_hold_val', '')))}</td></tr>"
        )

    plot_thumbnails = []
    for name, rel in plot_files.items():
        if rel:
            plot_thumbnails.append(
                f"<h3>{html.escape(name)}</h3><img src=\"{html.escape(rel)}\" "
                "style=\"max-width: 100%; border: 1px solid #ddd; margin-bottom: 12px;\" />"
            )

    html_text = f"""<!DOCTYPE html>
<html>
<head>
  <meta charset=\"utf-8\" />
  <title>Run Export Analysis</title>
  <style>
    body {{font-family: Arial, sans-serif; margin: 24px; color: #111;}}
    table {{border-collapse: collapse; width: 100%; font-size: 12px;}}
    th, td {{border: 1px solid #ddd; padding: 6px;}}
    th {{background: #f5f5f5;}}
    h2 {{margin-top: 28px;}}
    .muted {{color: #666;}}
  </style>
</head>
<body>
  <h1>Run Export Analysis</h1>
  <p class=\"muted\">Run: {html.escape(str(run_dir))}</p>
  <p class=\"muted\">Generated at: {html.escape(generated_at)}</p>
  <h2>Artifacts</h2>
  <ul>
    <li>analysis_report.json</li>
    <li>analysis_summary.csv</li>
    <li>analysis_metrics_long.csv ({metric_points} rows)</li>
    <li>analysis_training_long.csv ({training_points} rows)</li>
    <li>analysis_tooltips.csv</li>
  </ul>
  <h2>Files</h2>
  <pre>{html.escape(json.dumps(generated_files, indent=2))}</pre>

  <h2>Metric comparison summary</h2>
  <table>
    <thead>
      <tr>
        <th>metric</th>
        <th>label</th>
        <th>risk</th>
        <th>synth->val</th>
        <th>synth->hold</th>
        <th>hold->val</th>
        <th>relative gap</th>
      </tr>
    </thead>
    <tbody>
      {''.join(table_rows)}
    </tbody>
  </table>

  <h2>Tooltips</h2>
  <table>
    <thead>
      <tr>
        <th>metric_id</th>
        <th>description</th>
        <th>preferred direction</th>
      </tr>
    </thead>
    <tbody>
      {''.join(tooltip_cells)}
    </tbody>
  </table>

  <h2>Generated plots</h2>
  {''.join(plot_thumbnails)}
</body>
</html>
"""
    output_path.write_text(html_text, encoding="utf-8")


def _format_plot_status_badge(is_generated: bool) -> str:
    return "ok" if is_generated else "missing"


def _render_html_report(
    output_path: Path,
    run_dir: Path,
    metrics_summary: list[dict[str, Any]],
    generated_at: str,
    generated_files: Mapping[str, str],
    plot_files: Mapping[str, str],
    plot_generation: Mapping[str, Any],
    tooltips: Mapping[str, Mapping[str, str]],
) -> None:
    metric_rows = sorted(
        [row for row in metrics_summary if row.get("metric_key") not in {None, ""}],
        key=lambda item: (str(item.get("metric_family")), str(item.get("metric_key"))),
    )

    risk_counts = {
        "low": sum(1 for row in metric_rows if row.get("risk_level") == "low"),
        "medium": sum(1 for row in metric_rows if row.get("risk_level") == "medium"),
        "high": sum(1 for row in metric_rows if row.get("risk_level") == "high"),
        "unknown": sum(1 for row in metric_rows if row.get("risk_level") not in {"low", "medium", "high"}),
    }

    metric_rows_html = []
    for row in metric_rows:
        metric_rows_html.append(
            "<tr>"
            f"<td>{html.escape(str(row.get('metric_key', '')))}</td>"
            f"<td>{html.escape(str(row.get('metric_label', '')))}</td>"
            f"<td>{html.escape(str(row.get('metric_family', '')))}</td>"
            f"<td>{_to_html_value(row.get('synth_to_val'))}</td>"
            f"<td>{_to_html_value(row.get('synth_to_hold'))}</td>"
            f"<td>{_to_html_value(row.get('hold_to_val'))}</td>"
            f"<td><span class=\"risk-pill {_risk_badge_class(str(row.get('risk_level')))}\">"
            f"{html.escape(str(row.get('risk_level', 'unknown')))}</span></td>"
            f"<td>{_to_html_value(row.get('relative_gap_to_hold_val'), precision=4)}</td>"
            f"<td>{_to_html_value(row.get('abs_gap_to_hold_val'), precision=4)}</td>"
            f"<td>{_to_html_value(row.get('description', ''))}</td>"
            "</tr>"
        )

    tooltip_rows_html = []
    for row in sorted(tooltips.values(), key=lambda item: str(item.get("metric_id"))):
        tooltip_rows_html.append(
            "<tr>"
            f"<td>{html.escape(str(row.get('metric_id', '')))}</td>"
            f"<td>{html.escape(str(row.get('metric_name', '')))}</td>"
            f"<td>{html.escape(str(row.get('metric_family', '')))}</td>"
            f"<td>{html.escape(str(row.get('preferred_direction', '')))}</td>"
            f"<td>{html.escape(str(row.get('description', '')))}</td>"
            f"<td>{_to_html_label(row.get('lower_is_better') == 'true')}</td>"
            "</tr>"
        )

    plot_plan = [
        ("comparison_plot", "comparison_metrics", "Family-level metric comparison"),
        ("leakage_plot", "comparison_leakage", "Relative split deviation"),
        ("training_plot", "training_curves", "Training time-series"),
    ]
    plot_cards = []
    for key, title, subtitle in plot_plan:
        outputs = plot_generation.get("outputs", {})
        status = outputs.get(key, {})
        generated = bool(status.get("generated", False))
        path = status.get("path") or plot_files.get(key, "")
        reason = status.get("reason", "")
        status_text = _format_plot_status_badge(generated)
        badge_class = "risk-low" if generated else "risk-high"
        plot_path = output_path.parent / str(path) if path else None
        image = (
            f"<img src='{html.escape(str(path))}' alt='{html.escape(title)}'/>"
            if path and plot_path is not None and plot_path.exists()
            else "<p class='muted'>No image file was generated.</p>"
        )
        plot_cards.append(
            "<article class='plot-card'>"
            f"<h3>{html.escape(title)} <span class='plot-chip'>{html.escape(status_text)}</span></h3>"
            f"<p class='muted'>{html.escape(subtitle)}</p>"
            f"<p class='muted'>Path: {html.escape(str(path) if path else 'n/a')} · "
            f"Reason: {html.escape(str(reason) if reason else 'generated' if generated else 'not_available')}</p>"
            f"<p class='muted'><span class='{badge_class}'>"
            f"{'generated' if generated else 'missing'}</span></p>"
            f"{image}"
            "</article>"
        )

    html_text = f"""<!DOCTYPE html>
<html>
<head>
  <meta charset=\"utf-8\" />
  <title>Run Export Analysis</title>
  <style>
    :root {{
      --bg: #f8fafc;
      --text: #0f172a;
      --muted: #64748b;
      --line: #dbe0ea;
      --panel: #ffffff;
      --risk-low: #166534;
      --risk-medium: #92400e;
      --risk-high: #991b1b;
      --risk-unknown: #334155;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      font-family: "Inter", "Segoe UI", Arial, sans-serif;
      background: radial-gradient(circle at 20% -20%, #bfdbfe40, transparent 45%), radial-gradient(circle at 80% 0%, #ddd6fe40, transparent 35%), var(--bg);
      color: var(--text);
    }}
    .page {{ max-width: 1200px; margin: 0 auto; padding: 24px 16px 40px; }}
    h1, h2, h3 {{ margin: 0; }}
    h2 {{ margin-top: 20px; font-size: 1.22rem; }}
    .panel {{ background: var(--panel); border: 1px solid var(--line); border-radius: 12px; padding: 16px; margin-top: 14px; }}
    .muted {{ color: var(--muted); }}
    .kpis {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 10px; }}
    .kpi {{ border: 1px solid var(--line); border-radius: 10px; padding: 9px; background: #f8fafc; }}
    .kpi .value {{ font-size: 1.2rem; font-weight: 700; }}
    .kpi .label {{ font-size: 0.76rem; text-transform: uppercase; letter-spacing: 0.4px; color: var(--muted); }}
    .grid-two {{ display: grid; grid-template-columns: 1.1fr 1fr; gap: 12px; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 0.9rem; }}
    th, td {{ border-bottom: 1px solid var(--line); padding: 8px 7px; text-align: left; white-space: nowrap; }}
    th {{ background: #f1f5f9; color: #334155; text-transform: uppercase; font-size: 0.74rem; }}
    td {{ vertical-align: top; }}
    .desc-cell {{ max-width: 280px; white-space: normal; }}
    .risk-low {{ background: #dcfce7; color: var(--risk-low); }}
    .risk-medium {{ background: #fef9c3; color: var(--risk-medium); }}
    .risk-high {{ background: #fee2e2; color: var(--risk-high); }}
    .risk-unknown {{ background: #e2e8f0; color: var(--risk-unknown); }}
    .risk-pill {{ display: inline-block; padding: 2px 8px; border-radius: 999px; font-size: 0.73rem; font-weight: 700; }}
    .table-wrap {{ overflow: auto; margin-top: 10px; }}
    .plot-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 10px; }}
    .plot-card {{ border: 1px solid var(--line); border-radius: 10px; padding: 10px; background: #fff; }}
    .plot-card h3 {{ font-size: 0.96rem; margin-bottom: 4px; }}
    .plot-chip {{ border: 1px solid var(--line); border-radius: 999px; padding: 1px 7px; font-size: 0.7rem; }}
    .plot-card img {{ width: 100%; display: block; border-radius: 8px; border: 1px solid var(--line); }}
    @media (max-width: 900px) {{ .grid-two {{ grid-template-columns: 1fr; }} }}
    pre {{ margin: 0; font-size: 0.74rem; white-space: pre-wrap; }}
  </style>
</head>
<body>
  <main class='page'>
    <section class='panel'>
      <h1>Run Export Analysis</h1>
      <p class='muted'>Run: {html.escape(str(run_dir))}</p>
      <p class='muted'>Generated at: {html.escape(generated_at)}</p>
      <div class='kpis'>
        <div class='kpi'><div class='value'>{len(metric_rows)}</div><div class='label'>Metric rows</div></div>
        <div class='kpi'><div class='value'>{risk_counts['low']}</div><div class='label'>Low risk</div></div>
        <div class='kpi'><div class='value'>{risk_counts['medium']}</div><div class='label'>Medium risk</div></div>
        <div class='kpi'><div class='value'>{risk_counts['high']}</div><div class='label'>High risk</div></div>
        <div class='kpi'><div class='value'>{risk_counts['unknown']}</div><div class='label'>Unknown risk</div></div>
      </div>
    </section>

    <section class='panel'>
      <h2>Artifacts</h2>
      <div class='grid-two'>
        <ul class='muted'>
          <li>{html.escape(generated_files.get('analysis_report_json', ''))}</li>
          <li>{html.escape(generated_files.get('analysis_summary_csv', ''))}</li>
          <li>{html.escape(generated_files.get('analysis_metrics_long_csv', ''))}</li>
          <li>{html.escape(generated_files.get('analysis_training_long_csv', ''))}</li>
          <li>{html.escape(generated_files.get('analysis_tooltips_csv', ''))}</li>
        </ul>
        <pre>{html.escape(json.dumps(generated_files, indent=2))}</pre>
      </div>
      <p class='muted'>matplotlib available: {html.escape(str(plot_generation.get("plot_library_available", False)))}</p>
    </section>

    <section class='panel'>
      <h2>Metric comparison summary</h2>
      <div class='table-wrap'>
        <table>
          <thead>
            <tr>
              <th>Metric</th>
              <th>Label</th>
              <th>Family</th>
              <th>Synth→Val</th>
              <th>Synth→Hold</th>
              <th>Hold→Val</th>
              <th>Risk</th>
              <th>Relative gap</th>
              <th>Abs gap</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            {''.join(metric_rows_html)}
          </tbody>
        </table>
      </div>
    </section>

    <section class='panel'>
      <h2>Metric definitions</h2>
      <div class='table-wrap'>
        <table>
          <thead>
            <tr>
              <th>Metric ID</th>
              <th>Name</th>
              <th>Family</th>
              <th>Preferred</th>
              <th>Description</th>
              <th>Lower is better</th>
            </tr>
          </thead>
          <tbody>
            {''.join(tooltip_rows_html)}
          </tbody>
        </table>
      </div>
    </section>

    <section class='panel'>
      <h2>Generated plots</h2>
      <p class='muted'>A missing plot usually means missing data rows or no plot dependency in the environment.</p>
      <div class='plot-grid'>{''.join(plot_cards)}</div>
    </section>
  </main>
</body>
</html>
"""
    output_path.write_text(html_text, encoding="utf-8")


def analyze_run_exports(
    *,
    run_dir: Path,
    metrics_export_json: Path | None = None,
    training_export_json: Path | None = None,
    output_dir: Path | None = None,
    analyze_metrics: bool = True,
    analyze_training: bool = True,
    strict: bool = False,
    no_plots: bool = False,
) -> dict[str, Any]:
    run_dir = Path(run_dir)
    output_dir = Path(output_dir) if output_dir is not None else run_dir / ANALYSIS_DIR_NAME
    output_dir.mkdir(parents=True, exist_ok=True)
    figures_dir = output_dir / OUTPUT_FIG_DIR
    figures_dir.mkdir(parents=True, exist_ok=True)

    output_json = output_dir / OUTPUT_JSON
    summary_csv = output_dir / OUTPUT_SUMMARY_CSV
    metrics_csv = output_dir / OUTPUT_METRICS_CSV
    training_csv = output_dir / OUTPUT_TRAINING_CSV
    tooltips_csv = output_dir / OUTPUT_TOOLTIPS_CSV
    html_report = output_dir / OUTPUT_HTML

    if metrics_export_json is None:
        metrics_export_json = run_dir / "metrics" / "metrics_export.json"
    if training_export_json is None:
        training_export_json = run_dir / "training" / "training_export.json"

    metrics_bundle: Mapping[str, Any] | None = None
    training_bundle: Mapping[str, Any] | None = None
    metrics_sections: Mapping[str, Mapping[str, Any]] = {}
    training_sections: Mapping[str, Mapping[str, Any]] = {}
    metrics_generated_at = None
    training_generated_at = None

    if analyze_metrics:
        if not metrics_export_json.exists():
            msg = f"missing metrics export: {metrics_export_json}"
            if strict:
                raise FileNotFoundError(msg)
            print(f"[analyze] warning: {msg}")
        else:
            metrics_bundle = _read_json(metrics_export_json)
            metrics_sections = _flatten_sections(metrics_bundle)
            metrics_generated_at = metrics_bundle.get("generated_at")
    if analyze_training:
        if not training_export_json.exists():
            msg = f"missing training export: {training_export_json}"
            if strict:
                raise FileNotFoundError(msg)
            print(f"[analyze] warning: {msg}")
        else:
            training_bundle = _read_json(training_export_json)
            training_sections = _flatten_sections(training_bundle)
            training_generated_at = training_bundle.get("generated_at")

    metrics_rows: list[dict[str, Any]] = []
    metric_summary_rows: list[dict[str, Any]] = []
    training_rows: list[dict[str, Any]] = []
    if analyze_metrics and metrics_bundle is not None:
        metrics_rows, metric_summary_rows = _collect_metric_comparison_rows(metrics_sections)
        _write_csv(metrics_csv, metrics_rows, [
            "record_type",
            "metric_family",
            "metric_key",
            "metric_label",
            "direction",
            "run_section",
            "value",
            "value_type",
            "lower_is_better",
            "status",
            "source_file",
            "tooltip_id",
            "description",
        ])

    if analyze_training and training_bundle is not None:
        training_rows = _collect_training_time_series_rows(run_dir=run_dir, training_sections=training_sections)
        if training_rows:
            _write_csv(training_csv, training_rows, [
                "record_type",
                "run_section",
                "artifact_name",
                "metric_name",
                "step_axis",
                "step",
                "value",
                "value_type",
                "status",
                "source_file",
            ])
        else:
            # keep an empty placeholder file for deterministic tooling
            _write_csv(training_csv, [], [
                "record_type",
                "run_section",
                "artifact_name",
                "metric_name",
                "step_axis",
                "step",
                "value",
                "value_type",
                "status",
                "source_file",
            ])

    tooltips = _build_tooltips()
    _write_tooltips_csv(tooltips_csv)

    training_summary = (
        dict(training_bundle.get("summary", {})) if isinstance(training_bundle, Mapping) else {}
    )
    summary_rows = _collect_summary_rows(
        run_dir=run_dir,
        metrics_summary_rows=metric_summary_rows,
        training_summary=training_summary,
        include_metrics=analyze_metrics and bool(metrics_rows),
        include_training=analyze_training and bool(training_summary),
        tooltips=tooltips,
    )
    _write_csv(summary_csv, summary_rows, [
        "record_type",
        "metric_family",
        "metric_key",
        "metric_label",
        "value",
        "lower_is_better",
        "tooltip_id",
        "synth_to_val",
        "synth_to_hold",
        "hold_to_val",
        "abs_gap_to_hold_val",
        "relative_gap_to_hold_val",
        "generalization_shift",
        "risk_level",
        "description",
        "status",
    ])

    plot_files: dict[str, str] = {}
    plot_generation: dict[str, Any] = {
        "requested": not no_plots,
        "plot_library_available": PLOT_LIB_AVAILABLE,
        "outputs": {
            "comparison_plot": {"generated": False, "path": "", "reason": "not_attempted"},
            "leakage_plot": {"generated": False, "path": "", "reason": "not_attempted"},
            "training_plot": {"generated": False, "path": "", "reason": "not_attempted"},
        },
    }

    if not no_plots:
        comparison_plot = figures_dir / OUTPUT_FIG_COMPARISON
        comparison_generated, comparison_reason = _build_comparison_plot(
            metric_summary_rows, comparison_plot
        )
        if comparison_generated:
            plot_files["comparison_plot"] = str(comparison_plot.relative_to(output_dir))
        plot_generation["outputs"]["comparison_plot"] = {
            "generated": comparison_generated,
            "path": str(comparison_plot.relative_to(output_dir)),
            "reason": comparison_reason,
        }
        leakage_plot = figures_dir / OUTPUT_FIG_LEAKAGE
        leakage_generated, leakage_reason = _build_leakage_plot(metric_summary_rows, leakage_plot)
        if leakage_generated:
            plot_files["leakage_plot"] = str(leakage_plot.relative_to(output_dir))
        plot_generation["outputs"]["leakage_plot"] = {
            "generated": leakage_generated,
            "path": str(leakage_plot.relative_to(output_dir)),
            "reason": leakage_reason,
        }
        training_plot = figures_dir / OUTPUT_FIG_TRAINING
        training_generated, training_reason = _build_training_plot(training_rows, training_plot)
        if training_generated:
            plot_files["training_plot"] = str(training_plot.relative_to(output_dir))
        plot_generation["outputs"]["training_plot"] = {
            "generated": training_generated,
            "path": str(training_plot.relative_to(output_dir)),
            "reason": training_reason,
        }
    else:
        for plot_key in plot_generation["outputs"]:
            plot_generation["outputs"][plot_key]["reason"] = "disabled_by_flag"

    generated_at = datetime.now(timezone.utc).isoformat()
    report_payload: dict[str, Any] = {
        "schema_version": ANALYSIS_SCHEMA_VERSION,
        "generated_at": generated_at,
        "run_dir": str(run_dir),
        "input": {
            "run_dir": str(run_dir),
            "metrics_export_json": str(metrics_export_json),
            "training_export_json": str(training_export_json),
            "analyze_metrics": analyze_metrics,
            "analyze_training": analyze_training,
            "strict": strict,
            "no_plots": no_plots,
            "metrics_export_generated_at": metrics_generated_at,
            "training_export_generated_at": training_generated_at,
        },
        "summary": {
            "generated_rows": {
                "metrics_long": len(metrics_rows),
                "training_long": len(training_rows),
                "tooltips": len(tooltips),
            },
            "risk_count": {
                "low": sum(
                    1 for row in metric_summary_rows if row.get("risk_level") == "low"
                ),
                "medium": sum(
                    1 for row in metric_summary_rows if row.get("risk_level") == "medium"
                ),
                "high": sum(
                    1 for row in metric_summary_rows if row.get("risk_level") == "high"
                ),
                "unknown": sum(
                    1 for row in metric_summary_rows if row.get("risk_level") == "unknown"
                ),
            },
        },
        "metric_comparisons": metric_summary_rows,
        "training_summary": training_summary,
        "generated_files": {
            "output_dir": str(output_dir),
            "analysis_report_json": str(output_json),
            "analysis_summary_csv": str(summary_csv),
            "analysis_metrics_long_csv": str(metrics_csv),
            "analysis_training_long_csv": str(training_csv),
            "analysis_tooltips_csv": str(tooltips_csv),
            "analysis_report_html": str(html_report),
            "figures_dir": str(figures_dir),
            **{name: str(path) for name, path in plot_files.items()},
        },
        "plot_generation": plot_generation,
    }
    output_json.write_text(json.dumps(report_payload, indent=2, ensure_ascii=False), encoding="utf-8")

    _render_html_report(
        output_path=html_report,
        run_dir=run_dir,
        metrics_summary=metric_summary_rows,
        generated_at=generated_at,
        generated_files=report_payload["generated_files"],
        plot_files=plot_files,
        plot_generation=plot_generation,
        tooltips=tooltips,
    )

    return report_payload


def _resolve_bool(raw: str | None) -> bool:
    if raw is None:
        return True
    if raw.lower() in {"1", "true", "yes", "y", "on"}:
        return True
    if raw.lower() in {"0", "false", "no", "n", "off"}:
        return False
    raise argparse.ArgumentTypeError(f"invalid boolean value: {raw}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate analysis and plots from run export artifacts.")
    parser.add_argument("--run-dir", type=Path, required=True, help="Run directory with metrics/training exports.")
    parser.add_argument("--metrics-export-json", type=Path, default=None, help="Path to metrics_export.json.")
    parser.add_argument("--training-export-json", type=Path, default=None, help="Path to training_export.json.")
    parser.add_argument("--output-dir", type=Path, default=None, help="Output directory for analysis artifacts.")
    parser.add_argument("--analysis-dir", type=Path, default=None, help="Alias for --output-dir.")
    parser.add_argument("--strict", action="store_true", help="Fail if any requested export artifact is missing.")
    parser.add_argument("--analyze-metrics", type=_resolve_bool, default=True, help="Analyze metric export (true/false).")
    parser.add_argument("--analyze-training", type=_resolve_bool, default=True, help="Analyze training export (true/false).")
    parser.add_argument("--no-plots", action="store_true", help="Do not render PNG plots.")
    args = parser.parse_args()

    output_dir = args.output_dir
    if output_dir is None and args.analysis_dir is not None:
        output_dir = args.analysis_dir

    analyze_run_exports(
        run_dir=args.run_dir,
        metrics_export_json=args.metrics_export_json,
        training_export_json=args.training_export_json,
        output_dir=output_dir,
        analyze_metrics=args.analyze_metrics if isinstance(args.analyze_metrics, bool) else True,
        analyze_training=args.analyze_training if isinstance(args.analyze_training, bool) else True,
        strict=args.strict,
        no_plots=args.no_plots,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
