import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

# Data paths
REAL_DATA_PATH = "data/viagens_lat_long.parquet"
DATETIME_COL = "tpep_pickup_datetime"
PICKUP_ID_COL = "PULocationID"
DROPOFF_ID_COL = "DOLocationID"

# Time filters
FILTER_YEAR = 2024
FILTER_MONTHS = [4, 5]
FILTER_DOW_MIN = 0
FILTER_DOW_MAX = 5
FILTER_START_DATE = None
FILTER_END_DATE = None

# Split fractions (70% train, 15% val, 15% hold)
# If TRAIN_FRAC + VAL_FRAC == 1.0, hold_df can be empty and val_df is used as final test.
# The model uses val_df for early stopping and for final evaluation.
TRAIN_FRAC = 0.70
VAL_FRAC = 0.15

# Model hyperparameters
ENCODER_HIDDEN_DIMS = (256, 128)
DECODER_HIDDEN_DIMS = (128, 128)
LATENT_DIM = 32
BATCH_SIZE = 1024
EPOCHS = 30
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 0.0
PICKUP_LOSS_WEIGHT = 1.2
DROPOFF_LOSS_WEIGHT = 1.2
PAIR_KL_WEIGHT = 1.0
PAIR_KL_EPS = 1e-6
PICKUP_KL_WEIGHT = 1.0
PICKUP_KL_EPS = 1e-6

# KL annealing
KL_BETA_START = 0.0
KL_BETA_END = 1.0
KL_ANNEAL_EPOCHS = 10

# Early stopping
PATIENCE = 8
MIN_DELTA = 1e-4

# Order for autoregressive decoder (fixed to order_1)
ORDERS = {
    "order_1": ["pickup_id", "dropoff_id", "day_of_week", "hour_of_day"],
}
FIXED_ORDER_KEY = "order_1"

OUTPUT_COLUMNS = ["hour_of_day", "day_of_week", "pickup_id", "dropoff_id"]
PASSENGER_COL = "passenger_count"
FARE_COL = "total_amount"
R_COL = "r"
THT_ATTRIBUTE_DISCRETE_COLUMNS = ["passenger_count"]
THT_ATTRIBUTE_CONTINUOUS_COLUMNS = ["total_amount"]

# Sampling
SAMPLE_TEMPERATURE = 1.0
SAMPLE_ROWS = 20000
EVAL_SAMPLE_RATIO = 1.0  # Use 100% of the evaluation split for metric computation.
MAX_EVAL_SAMPLES = None
TVAE_FLOW_DIAG_EVERY_EPOCHS = 0
TVAE_MONITOR_METRICS_EVERY_EPOCHS = 5
TVAE_MONITOR_MAX_SAMPLES = 5000

# Paper metrics
# Time slots per week after excluding Sunday (day 6 is omitted by FILTER_DOW_MAX=5)
TIME_KEY_CARDINALITY = 6 * 24
TIME_PERIOD_DOW = 6  # Days 0-5 (Monday-Saturday)
TIME_PERIOD_HOUR = 24
COVERAGE_K = 5
COVERAGE_MAX_SAMPLES = 100000
COVERAGE_CHUNK_SIZE = 512
COVERAGE_TIME_WEIGHT = 1.0
COVERAGE_SPACE_WEIGHT = 1.0
COVERAGE_RESIDUAL_WEIGHT = 1.0
DISTANCE_USE_RESIDUAL = True
DISTANCE_RESIDUAL_COL = "r"
DCR_ALPHA = 0.05
DCR_MAX_SAMPLES = 20000
DCR_CHUNK_SIZE = 1024
DCR_EPS = 1e-12
DCR_RESIDUAL_WEIGHT = 1.0
DCR_ALPHAS = [0.05, 0.01, 0.005]
DCR_W_TIME = 1.0
DCR_W_SPACE = 1.0
DCR_W_R = 0.5
DCR_W_PAX = 0.5
DCR_W_FARE = 0.5
DCR_FARE_SCALE_METHOD = "iqr"
DCR_SCALE_EPS = 1e-6

# Attribute metrics (fare/passenger_count)
EVAL_ENABLE_ATTRIBUTE_METRICS = True
EVAL_ENABLE_EXTENDED_PRIVACY = True

# Misc
GLOBAL_SEED = 42
NUM_WORKERS = 8
CUDNN_DETERMINISTIC = False
CUDNN_BENCHMARK = True

# Logging/monitoring
LOG_ENABLE_TENSORBOARD = True
LOG_FLUSH_EVERY = 50
LOG_BATCH_EVERY = 200  # 0 disables batch logging
METRICS_MONITOR_EVERY_EPOCHS = 5
METRICS_MONITOR_MAX_SAMPLES = 5000
METRICS_MONITOR_COVERAGE = False
METRICS_COMPUTE_RR_BASELINES = True
METRICS_RR_BOOTSTRAP_SEED = GLOBAL_SEED

# Privacy audit (THT-TripGen)
PRIVACY_REPORT_ENABLE = True
PRIVACY_MATCH_R_DECIMALS = 2
PRIVACY_REJECTION_ENABLE = False
PRIVACY_REJECTION_TAU = 0.05
PRIVACY_REJECTION_MAX_ITERS = 20

# THT-TripGen (hierarchical time + conditionals + alternative splits)
THT_TIME_BINS_H = 24
THT_EPOCHS = 30
THT_BATCH_SIZE = 4096  # Tune upward until near GPU memory limit; keep headroom on 24GB GPUs.
THT_LR = 3e-4 # 1e-3
THT_WEIGHT_DECAY = 0.0
THT_GRAD_CLIP_NORM = 2.0  # 0 disables clipping
THT_EVAL_SAMPLE_RATIO = 1.0
THT_LOG_BATCH_EVERY = 0
THT_FLOW_DIAG_EVERY_EPOCHS = 1
THT_MONITOR_METRICS_EVERY_EPOCHS = 5
THT_MONITOR_MAX_SAMPLES = 5000
THT_MONITOR_DO_COVERAGE = False
THT_MONITOR_COVERAGE_MAX_SAMPLES = 2000
THT_NUM_WORKERS = 8
THT_PIN_MEMORY = True
THT_PERSISTENT_WORKERS = True
THT_PREFETCH_FACTOR = 2
THT_MIN_R_EPS = 1e-6
THT_SPLIT_STRATEGY = "S1"  # "S1" (weekly chronological) or "S2" (by day)
THT_TRAIN_FRAC = 0.70
THT_VAL_FRAC = 0.15
THT_SPLIT_SEED = GLOBAL_SEED
THT_USE_WEEKEND = False
THT_USE_MONTH = False
THT_USE_PASSENGER_COUNT = True
THT_PASSENGER_COUNT_COL_RAW = "passenger_count"
THT_USE_TOTAL_AMOUNT = True
THT_TOTAL_AMOUNT_COL_RAW = "total_amount"
THT_DROP_NEGATIVE_TOTAL_AMOUNT = True
THT_TOTAL_AMOUNT_LOG1P = True
THT_TOTAL_AMOUNT_CLIP_PMIN = 0.001
THT_TOTAL_AMOUNT_CLIP_PMAX = 0.999
THT_TOTAL_AMOUNT_SIGMA_FLOOR = 1e-4
THT_TRIPGEN_COLUMNS = [
    "hour_of_day",
    "r",
    "pickup_id",
    "dropoff_id",
    "day_of_week",
]
if THT_USE_PASSENGER_COUNT and "passenger_count" not in THT_TRIPGEN_COLUMNS:
    THT_TRIPGEN_COLUMNS.append("passenger_count")
if THT_USE_TOTAL_AMOUNT and "total_amount" not in THT_TRIPGEN_COLUMNS:
    THT_TRIPGEN_COLUMNS.append("total_amount")
THT_FILTER_YEAR = FILTER_YEAR
THT_FILTER_MONTHS = FILTER_MONTHS
THT_FILTER_DOW_MIN = FILTER_DOW_MIN
THT_FILTER_DOW_MAX = FILTER_DOW_MAX
THT_FILTER_START_DATE = FILTER_START_DATE
THT_FILTER_END_DATE = FILTER_END_DATE
THT_NODE2VEC_DIM = 64
THT_NODE2VEC_WALKS_PER_NODE = 10
THT_NODE2VEC_WALK_LENGTH = 80
THT_NODE2VEC_WINDOW = 10
THT_NODE2VEC_P = 1.0
THT_NODE2VEC_Q = 1.0
THT_GFUNC_TOPK = 100
THT_PHYS_EDGES_CSV = "data/topology/tht_phys_edges_S1.csv"
THT_MODEL_DROPOUT = 0.1
THT_MODEL_HIDDEN = 256
THT_MODEL_LAYERS = 3
THT_COND_EMB_DIM = 16
THT_TIME_EMB_DIM = 16
THT_ORIGIN_EMB_DIM = 32
THT_DEST_HEAD_TYPE = "embedding_softmax"
THT_HYBRID_RESIDUAL_HIDDEN = 128
THT_HYBRID_RESIDUAL_WEIGHT_INIT = 1.0
THT_SAMPLE_TEMPERATURE = 1.0
THT_DESTINATION_HEAD_TYPE = THT_DEST_HEAD_TYPE
THT_TEMPERATURE = THT_SAMPLE_TEMPERATURE
THT_RESIDUAL_NUM_LAYERS = 5
THT_RESIDUAL_NUM_BINS = 8
THT_RESIDUAL_CONTEXT_HIDDEN = 256
THT_RESIDUAL_EPS = THT_MIN_R_EPS
THT_RESIDUAL_MIN_BIN_WIDTH = 1e-3
THT_RESIDUAL_MIN_BIN_HEIGHT = 1e-3
THT_RESIDUAL_MIN_DERIV = 1e-3

# Output dirs (all analyses/csvs under /home-ext/caioloss/Dados)
OUTPUT_BASE_DIR = Path("outputs")
SAVE_DATA_SUBDIR = "ryc"
SAVE_DATA_DIR = str(OUTPUT_BASE_DIR / "save_data" / SAVE_DATA_SUBDIR)
LOG_DIR = str(OUTPUT_BASE_DIR / "logs")
PLOT_DIR = str(OUTPUT_BASE_DIR / "plots")
THT_TOPOLOGY_CACHE_DIR = str(OUTPUT_BASE_DIR / "topology_cache")

for _d in (SAVE_DATA_DIR, LOG_DIR, PLOT_DIR, THT_TOPOLOGY_CACHE_DIR):
    os.makedirs(_d, exist_ok=True)

# Experiment overrides (train only order_1 with different params)
EXPERIMENTS = {
    "baseline": {},
}
