import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

# Data paths
REAL_DATA_PATH = "data/viagens_lat_long.parquet"
DATETIME_COL = "tpep_pickup_datetime"
PICKUP_ID_COL = "PULocationID"
DROPOFF_ID_COL = "DOLocationID"

# Time filters
FILTER_YEAR = 2024
FILTER_MONTHS = [4, 5]
FILTER_DOW_MIN = 0
FILTER_DOW_MAX = 5
FILTER_START_DATE = None
FILTER_END_DATE = None

# Split fractions (70% treino, 15% validação, 15% hold)
# Com TRAIN_FRAC + VAL_FRAC = 1.0, o hold_df fica vazio e val_df é usado como teste
# O modelo usa val_df tanto para early stopping quanto para avaliação final
TRAIN_FRAC = 0.70
VAL_FRAC = 0.15

# Model hyperparameters
ENCODER_HIDDEN_DIMS = (256, 128)
DECODER_HIDDEN_DIMS = (128, 128)
LATENT_DIM = 32
BATCH_SIZE = 1024
EPOCHS = 1 #30
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 0.0
PICKUP_LOSS_WEIGHT = 1.2
DROPOFF_LOSS_WEIGHT = 1.2
PAIR_KL_WEIGHT = 1.0
PAIR_KL_EPS = 1e-6
PICKUP_KL_WEIGHT = 1.0
PICKUP_KL_EPS = 1e-6

# KL annealing
KL_BETA_START = 0.0
KL_BETA_END = 1.0
KL_ANNEAL_EPOCHS = 10

# Early stopping
PATIENCE = 8
MIN_DELTA = 1e-4

# Order for autoregressive decoder (fixed to order_1)
ORDERS = {
    "order_1": ["pickup_id", "dropoff_id", "dia_da_semana", "hora_do_dia"],
}
FIXED_ORDER_KEY = "order_1"

OUTPUT_COLUMNS = ["hora_do_dia", "dia_da_semana", "pickup_id", "dropoff_id"]

# Sampling
SAMPLE_TEMPERATURE = 1.0
SAMPLE_ROWS = 20000
EVAL_SAMPLE_RATIO = 1.0  # 100% do teste para comparação equivalente
MAX_EVAL_SAMPLES = None
TVAE_FLOW_DIAG_EVERY_EPOCHS = 0
TVAE_MONITOR_METRICS_EVERY_EPOCHS = 5
TVAE_MONITOR_MAX_SAMPLES = 5000

# Paper metrics
# TIME_KEY_CARDINALITY = 6 * 24 porque domingo (dia 6) está excluído pelo filtro FILTER_DOW_MAX=5
TIME_KEY_CARDINALITY = 6 * 24
TIME_PERIOD_DOW = 6  # Dias 0-5 (seg-sáb)
TIME_PERIOD_HOUR = 24
COVERAGE_K = 5
COVERAGE_MAX_SAMPLES = 100000
COVERAGE_CHUNK_SIZE = 512
COVERAGE_TIME_WEIGHT = 1.0
COVERAGE_SPACE_WEIGHT = 1.0
DCR_ALPHA = 0.05
DCR_MAX_SAMPLES = 20000
DCR_CHUNK_SIZE = 1024
DCR_EPS = 1e-12

# Misc
GLOBAL_SEED = 42
NUM_WORKERS = 0

# Logging/monitoring
LOG_ENABLE_TENSORBOARD = True
LOG_FLUSH_EVERY = 50
LOG_BATCH_EVERY = 200  # 0 disables batch logging
METRICS_MONITOR_EVERY_EPOCHS = 5
METRICS_MONITOR_MAX_SAMPLES = 5000
METRICS_MONITOR_COVERAGE = False

# THT-TripGen (hierarchical time + conditionals + alternative splits)
THT_TIME_BINS_H = 24
THT_EPOCHS = 30
THT_BATCH_SIZE = 1024
THT_LR = 1e-3
THT_WEIGHT_DECAY = 0.0
THT_EVAL_SAMPLE_RATIO = 1.0
THT_LOG_BATCH_EVERY = 0
THT_FLOW_DIAG_EVERY_EPOCHS = 1
THT_MONITOR_METRICS_EVERY_EPOCHS = 5
THT_MONITOR_MAX_SAMPLES = 5000
THT_MONITOR_DO_COVERAGE = False
THT_MONITOR_COVERAGE_MAX_SAMPLES = 2000
THT_MIN_R_EPS = 1e-6
THT_SPLIT_STRATEGY = "S1"  # "S1" (weekly chronological) or "S2" (by day)
THT_TRAIN_FRAC = 0.70
THT_VAL_FRAC = 0.15
THT_SPLIT_SEED = GLOBAL_SEED
THT_USE_WEEKEND = False
THT_USE_MONTH = False
THT_TRIPGEN_COLUMNS = [
    "hora_do_dia",
    "r",
    "pickup_id",
    "dropoff_id",
    "dia_da_semana",
]
THT_FILTER_YEAR = FILTER_YEAR
THT_FILTER_MONTHS = FILTER_MONTHS
THT_FILTER_DOW_MIN = FILTER_DOW_MIN
THT_FILTER_DOW_MAX = FILTER_DOW_MAX
THT_FILTER_START_DATE = FILTER_START_DATE
THT_FILTER_END_DATE = FILTER_END_DATE
THT_NODE2VEC_DIM = 64
THT_NODE2VEC_WALKS_PER_NODE = 10
THT_NODE2VEC_WALK_LENGTH = 80
THT_NODE2VEC_WINDOW = 10
THT_NODE2VEC_P = 1.0
THT_NODE2VEC_Q = 1.0
THT_GFUNC_TOPK = 100
THT_PHYS_EDGES_CSV = "data/topology/tht_phys_edges_S1.csv"
THT_MODEL_DROPOUT = 0.1
THT_MODEL_HIDDEN = 256
THT_MODEL_LAYERS = 3
THT_COND_EMB_DIM = 16
THT_TIME_EMB_DIM = 16
THT_ORIGIN_EMB_DIM = 32
THT_DEST_HEAD_TYPE = "embedding_softmax"
THT_SAMPLE_TEMPERATURE = 1.0
THT_DESTINATION_HEAD_TYPE = THT_DEST_HEAD_TYPE
THT_TEMPERATURE = THT_SAMPLE_TEMPERATURE
THT_RESIDUAL_NUM_LAYERS = 5
THT_RESIDUAL_NUM_BINS = 8
THT_RESIDUAL_CONTEXT_HIDDEN = 256
THT_RESIDUAL_EPS = THT_MIN_R_EPS
THT_RESIDUAL_MIN_BIN_WIDTH = 1e-3
THT_RESIDUAL_MIN_BIN_HEIGHT = 1e-3
THT_RESIDUAL_MIN_DERIV = 1e-3

# Output dirs (all analyses/csvs under /home-ext/caioloss/Dados)
OUTPUT_BASE_DIR = Path("outputs")
SAVE_DATA_SUBDIR = "ryc"
SAVE_DATA_DIR = str(OUTPUT_BASE_DIR / "save_data" / SAVE_DATA_SUBDIR)
LOG_DIR = str(OUTPUT_BASE_DIR / "logs")
PLOT_DIR = str(OUTPUT_BASE_DIR / "graficos")
THT_TOPOLOGY_CACHE_DIR = str(OUTPUT_BASE_DIR / "topology_cache")

for _d in (SAVE_DATA_DIR, LOG_DIR, PLOT_DIR, THT_TOPOLOGY_CACHE_DIR):
    os.makedirs(_d, exist_ok=True)

# Experiment overrides (train only order_1 with different params)
EXPERIMENTS = {
    "baseline": {},
}
